### ISSUE TITLE
17) Ask (Howdoi tool) not working, and fails to download 

### ISSUE THREAD

**Issue by fxgx99** [arismelachroinos/lscript#106]
After Launching the scritpt when I type 17 in order to get "Howdoi" I get the a message asking me to type 'install' But After that nothing happens and I get the following error message:

`Howdoi is not installed.type 'install' to install it.
install
/bin/lscript/l: line 9597: pip: command not found
/bin/lscript/l: line 9598: pip2.7: command not found
Press any key to go back...
`
is Anyone else experiencing the same problem?

**Comment by arismelachroinos** [comment]
Please install pip first

**Comment by arismelachroinos** [comment]
apt install python-pip

**Comment by ASOwnerYT** [comment]
Was having the same issue. Fixed now. Thanks.
