### ISSUE TITLE
How about runing this on iOS 7.2.1 jailbreak

### ISSUE THREAD

**Issue by 1anakin20** [arismelachroinos/lscript#108]
I jailbreak my iPhone 4, as iOS is based on UNIX , would be even possible to run lazy script on it? Hope you can tell me. And if it's possible how. Thanks

**Comment by razercortex101** [comment]
Maybe, maybe not. The script might not work and some tools may not work either. You can try by installing MobileTerminal from Cydia then running these commands: 
`cd
git clone https://github.com/arismelachroinos/lscript.git
cd lscript
chmod +x install.sh
./install.sh'

If it comes with an error, then tell me the output.

**Comment by razercortex101** [comment]
You might also need to install git.

**Comment by 1anakin20** [comment]
Installed git, run the commands, installation presented no error. Checked in the folder where it installed. Everything is there, the only problem is the command to launch it. When I use 'l' says command not found.

**Comment by razercortex101** [comment]
First of all, the script is for KALI LINUX ONLY. Second, try cd'ing to /bin/lscript and running ./l

**Comment by razercortex101** [comment]
`cd /
cd bin
cd lscript
./l`

**Comment by razercortex101** [comment]
Copy the code from above one line at a time.

**Comment by razercortex101** [comment]
Works fine on Android. Try it.

**Comment by 1anakin20** [comment]
Now I see a little more why it dosen't work. The access to /bin/lscript is denied. The folder lscript in bin is empty. When installing I noticed the output lines saying the access is denied

**Comment by razercortex101** [comment]
Ok, I kinda did know it wouldn't work on iOS.

**Comment by razercortex101** [comment]
And I do know it's locked down.

**Comment by 1anakin20** [comment]
Works in Android, cool new thing to try. In the meantime I will try to get it working on my Hackintosh. So yep make sense why it dosen't work on iOS, thanks for the help.

**Comment by VitorCoelho** [comment]
For god's sake,  get a room you 2! You do realize that you got hundreds of emails updating this?

**Comment by Ekultek** [comment]
@1anakin20 move it to user exec directories and it should work, might have to use brew in place though

**Comment by razercortex101** [comment]
I have a hackintosh too! :smile:
