### ISSUE TITLE
Parrot OS compability

### ISSUE THREAD

**Issue by jsSilence** [arismelachroinos/lscript#109]
If you install the lazy-script and wanna start it by typing "l" in a terminal you won't see the script. It just lists the dir. 

Please change this so Parrot OS users can use this awesome script too.

**Comment by Ekultek** [comment]
it's already compatible. remove the alias `l`. parrot is debian just like kali is...

**Comment by arismelachroinos** [comment]
Not designed for Parrot.

**Comment by kj4caq** [comment]
jsSilence

Try:

alias l='sudo /root/lscript/l'

Works on my parrot vm

**Comment by cjsatuforc** [comment]
thank you kj4caq! I was searching everywhere and this was the only thing that worked. i think i lost a bunch hair today.

**Comment by seib15855** [comment]
@z3r0Sec

**Comment by heydr6** [comment]
kj4caq heydrsimon6@gmail thanks for the lscript tip it worked i have trouble on my public private github add ssh keys on my parrot vb any ideas everywhere else no good

**Comment by abdelrahmanelmarakby** [comment]
you guys can install with Tool-X if you want
