### ISSUE TITLE
add tool

### ISSUE THREAD

**Issue by Nullifidian** [arismelachroinos/lscript#11]
https://github.com/s0lst1c3/eaphammer

eaphammer is the defacto wpa2 tool right now.. used in all corporate wifi pentests <3

**Comment by arismelachroinos** [comment]
Of course. I will check it out and maybe on the next update it will be included.

**Comment by arismelachroinos** [comment]
Added on the current update 2.0.2. Update the lscript by typing update, and then check it out in wifi tools. I made an automated menu just on that.
