### ISSUE TITLE
Parrot OS Permission denied

### ISSUE THREAD

**Issue by maed-ness** [arismelachroinos/lscript#110]
i installed lscript like i did many times on kali. now i try it the first time on Parrot os and i can't get it running. 
installed
"unalias l"
"l"
then it asks me about accepting the terms. i press a key, type in YES to accept the terms and i get this error: "ls script line 5979: root/lscript/IAGREE.txt: Permission denied"

Can someone help me? cheers.

**Comment by arismelachroinos** [comment]
Doesnt work on Parrot OS
