### ISSUE TITLE
Internet connection goes down when changing mac address

### ISSUE THREAD

**Issue by Gabrieldaboss65** [arismelachroinos/lscript#111]
Since it's pretty obvious that this feature just comes from macchanger I couldn't figure out how to fix this. Nothing I've tried works. I don't know if it could be that I'm visualizing but I have a bridged adapter configuration so I don't know. Had this issue before on macchanger.

**Comment by arismelachroinos** [comment]
Sorry this has nothing to do with the script, also I just checked that and it worked, however I do remember having the same issue in the past.
