### ISSUE TITLE
Tool Suggestion

### ISSUE THREAD

**Issue by DeaDHackS** [arismelachroinos/lscript#113]
ProCep which is a tool i made which generates payload to bypass every anti-viruses i did a check with online tools.

https://github.com/DeaDHackSTeam/ProCep---Strongly-Encrypted-Backdoor-Generator

To install:
cd /root/Desktop/
git clone https://github.com/DeaDHackSTeam/ProCep---Strongly-Encrypted-Backdoor-Generator 
Extract the file called ProCep in the file.
chmod 777 -R ProCep
cd ProCep/
./setup.sh

Ta da and yes it needs to be on the desktop i'm gonna to make update soon to change that.

Thanks if you accept it in ;D
Lots of love.

**Comment by arismelachroinos** [comment]
Thank you sir. Report back when it works on root. I am finishing with my exams and I will be updating lscript 😊

**Comment by DeaDHackS** [comment]
Thanks! Incoming update features:

Executable everywhere - no installation will be required anymore
Auto-listener generator and executor
Encrypt existing file/backdoor option in menu

Thats all! Suggest me anything i should add if possible and thanks! 😁😁😁

**Comment by DeaDHackS** [comment]
Also if interrested i'm working on Dooms which is a online/offline cracking password tools. Tell me if you would like to test it and add it maybe.

**Comment by arismelachroinos** [comment]
![image](https://user-images.githubusercontent.com/21193898/42679092-8544df52-8689-11e8-9179-2f10ed20fa7c.png)

**Comment by DeaDHackS** [comment]
Ummm wait, thats the old version! Get the new version man! That was the installler!
https://github.com/DeaDHackS/ProCep-V-1.0.2
This one doesn't require any installer only need to launch the procepmenu.sh to launch the tool.

**Comment by DeaDHackS** [comment]
Yeah sorry i abandonned this script, simply because GPG2 is not valid anymore in 2018.2-2018.1 and the script doesn't find the client key even its public, i'm working on a DoS tool written in perl if interrested.
