### ISSUE TITLE
ProCep V:1.0.6 is out and done! (Tool suggestion)

### ISSUE THREAD

**Issue by DeaDHackS** [arismelachroinos/lscript#114]
Hello! I have finish ProCep 2!
https://github.com/DeaDHackS/ProCep-V-1.0.2

 To use:
 cd /root/Desktop/ # Desktop directory is not needed anymore but its better to have it on desktop so access it quickly
git clone https://github.com/DeaDHackS/ProCep-V-1.0.2
extract ProCep file inside ProCep-V-1.0.2 folder
cd ProCep/
./procepmenu.sh

Ta da! Easy ;D 
Lots of love

**Comment by arismelachroinos** [comment]
Hi sir, thank you, I am going to take a look at it

**Comment by DeaDHackS** [comment]
Umm weird about the error it should have installed GPG2 in the setup... let me have a look really quick sorry about that.

**Comment by DeaDHackS** [comment]
Ok here i fixed it hopefully, i added this start up line:

gpg2 2>/dev/null 1>&2
ToolInstalled=$?

if [[ ToolInstalled = 0 ]]; then
   echo "Required Tool installed, displaying menu.."
   sleep2
elif [[ ToolInstalled = 1 ]]; then
   echo "Oops, seems a required tool is NOT installed."
   echo "Installaing..... (We don't ask to install since its a REQUIRED tool!)"
   apt-get install gpg2
   echo "Finish!"
fi

So it should check if gpg2 is installed and install it if not. Sorry for that error, i totally forgot i removed the setup file!

**Comment by DeaDHackS** [comment]
I can't remember if gpg2 is -h or --help... let me know if it works!
