### ISSUE TITLE
Lazy Script does not open

### ISSUE THREAD

**Issue by Matteo19** [arismelachroinos/lscript#118]
I installed it correctly:
chmod +x install.sh
./install.sh

but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".

Help me please!

**Comment by arismelachroinos** [comment]
At start up, it launches an ifconfig in the bg to select your interfaces. If that command is failing to load then the result is an empty terminal. Try to disconnect and reconnect your antenna. I might be making a mistake, I will take a look at it.

**Comment by LobodaPavel** [comment]
have the same problem

**Comment by FrisbTDW** [comment]
> I installed it correctly:
> chmod +x install.sh
> ./install.sh
> 
> but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".
> 
> Help me please!

frisb@DESKTOP-1TLC3SS:~/lscript$ l
bash: l: command not found

?????
what do i do?
how do i fix this error?(bash: l: command not found)

**Comment by FrisbTDW** [comment]
> At start up, it launches an ifconfig in the bg to select your interfaces. If that command is failing to load then the result is an empty terminal. Try to disconnect and reconnect your antenna. I might be making a mistake, I will take a look at it.

frisb@DESKTOP-1TLC3SS:~/lscript$ l
bash: l: command not found

?????
what do i do?
how do i fix this error?(bash: l: command not found

**Comment by EnkiFawkes** [comment]
> > At start up, it launches an ifconfig in the bg to select your interfaces. If that command is failing to load then the result is an empty terminal. Try to disconnect and reconnect your antenna. I might be making a mistake, I will take a look at it.
> 
> frisb@DESKTOP-1TLC3SS:~/lscript$ l
> bash: l: command not found
> 
> ?????
> what do i do?
> how do i fix this error?(bash: l: command not found
Try it it as root user, by 
su -s
Then try it,
you may need toi put bash command before it too like
./l
You may even need to go to the root directory
su -s
cd /root
cd lscript
./l

**Comment by iahmeddd** [comment]
Well After installation, first my ' l ' was not working. 
You just have to do alias to ' l ' command, 
run this command into your terminal as root
#alias l="/root/lscript/l"
but after restart it will not work, for permanent, you have to add that into bashsc 
#vim ~/.bashsc
go and stop when you see alias's and add that command there :) 
That will Work

**Comment by hyper1da** [comment]
> Well After installation, first my ' l ' was not working.
> You just have to do alias to ' l ' command,
> run this command into your terminal as root
> #alias l="/root/lscript/l"
> but after restart it will not work, for permanent, you have to add that into bashsc
> #vim ~/.bashsc
> go and stop when you see alias's and add that command there :)
> That will Work

I tried it but the same happens to me again and again. When I press "l" it shows me the files in root as does ls. Even if I go to lazyscript and type "l*" it shows that "-bash: l: command not found"

I did as you said so I dont understand the issue .

**Comment by 4thelight** [comment]
Here is the solution :-)

After installed------

make sure you have root:
Sudo su

cd lscript

bash l

**Comment by 4thelight** [comment]
> > Well After installation, first my ' l ' was not working.
> > You just have to do alias to ' l ' command,
> > run this command into your terminal as root
> > #alias l="/root/lscript/l"
> > but after restart it will not work, for permanent, you have to add that into bashsc
> > #vim ~/.bashsc
> > go and stop when you see alias's and add that command there :)
> > That will Work
> 
> I tried it but the same happens to me again and again. When I press "l" it shows me the files in root as does ls. Even if I go to lazyscript and type "l*" it shows that "-bash: l: command not found"
> 
> I did as you said so I dont understand the issue .

make sure you have root:
Sudo su

cd lscript

bash l

**Comment by 4thelight** [comment]
> > I installed it correctly:
> > chmod +x install.sh
> > ./install.sh
> > but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".
> > Help me please!
> 
> frisb@DESKTOP-1TLC3SS:~/lscript$ l
> bash: l: command not found
> 
> ?????
> what do i do?
> how do i fix this error?(bash: l: command not found)

make sure you have root:
Sudo su

cd lscript

bash l

**Comment by 4thelight** [comment]
> I installed it correctly:
> chmod +x install.sh
> ./install.sh
> 
> but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".
> 
> Help me please!

make sure you have root:
Sudo su

cd lscript

bash l

**Comment by 4thelight** [comment]
> > I installed it correctly:
> > chmod +x install.sh
> > ./install.sh
> > but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".
> > Help me please!
> 
> make sure you have root:
> Sudo su
> 
> cd lscript
> 
> bash l

in Terminal

**Comment by 4thelight** [comment]
make sure you have root:
Sudo su

cd lscript

bash l

you have to 

bash l     

again as your setting  it up

than access any time you have root in terminal with bash l

**Comment by mikelssa1** [comment]
./l

**Comment by www-h4k3r-com** [comment]
@4thelight  that works , thanks for the solution !!! :)

**Comment by 4thelight** [comment]
Yea I feel absolutely humbled being a newbie myself happy to help!

**Comment by bittu212121** [comment]
> I installed it correctly:
> chmod +x install.sh
> ./install.sh
> 
> but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".
> 
> Help me please!

Just try sudo bash l

this will work

**Comment by Hazey8709** [comment]
> > I installed it correctly:
> > chmod +x install.sh
> > ./install.sh
> > but when it finished the installation, if I type "l" open The Lazy Script window but there's no option to type, only the sentence that rename the window "THE LAZY SCRIPT".
> > Help me please!
> 
> make sure you have root:
> Sudo su
> 
> cd lscript
> 
> bash l

Somethings wrong cause this fixed my issue the lazy script menu popped up n use bash l   in terminal  or repeat if necessary

**Comment by Amogh-D-Prasanna** [comment]
> > > Well After installation, first my ' l ' was not working.
> > > You just have to do alias to ' l ' command,
> > > run this command into your terminal as root
> > > #alias l="/root/lscript/l"
> > > but after restart it will not work, for permanent, you have to add that into bashsc
> > > #vim ~/.bashsc
> > > go and stop when you see alias's and add that command there :)
> > > That will Work
> > 
> > 
> > I tried it but the same happens to me again and again. When I press "l" it shows me the files in root as does ls. Even if I go to lazyscript and type "l*" it shows that "-bash: l: command not found"
> > I did as you said so I dont understand the issue .
> 
> make sure you have root:
> Sudo su
> 
> cd lscript
> 
> bash l

thanks a lot, this did really work out for me

**Comment by Hazey8709** [comment]
Cool

**Comment by Hazey8709** [comment]
I noticed also which ever user you was when you installed  lscript with it will only work on that user and root  unless you give permission to another user (aka user name)

**Comment by Shaydude** [comment]
This totally works thanks
