### ISSUE TITLE
Can you make it compatible with Ubuntu?

### ISSUE THREAD

**Issue by iamrahatul** [arismelachroinos/lscript#125]
`There was an error creating the child process for this terminal`
`Failed to execute child process “bash /root/lscript/install.sh” (No such file or directory)`

**Comment by arismelachroinos** [comment]
No, sorry

**Comment by kumarlive21** [comment]
i have same problem Failed to execute child process “bash /root/lscript/install.sh” (No such file or directory)

**Comment by anonymouXnash** [comment]
I'm having the same issue and i don't know what to do... Can someone please help me out?

**Comment by Mouad67** [comment]
me too pleas help

**Comment by valen1321** [comment]
same here on kali linux

**Comment by barhouum7** [comment]
It's working fine on kali linux

**Comment by 0dinseye** [comment]
It’s not working on Kali . I’m having the same problem. I have Kali on a raspberry pi 4. I had a the same problem but I actually got lscript to run once and now it just keeps asking me to agree “YES” then never runs just a continuous loop asking me to except the terms and type YES, I type YES in all caps and it starts all over again but never opens. What the hell is the problem? Why is there nothing on the Internet addressing this issue? The lazy script is not so lazy it should be called the frustration script that never actually works!

**Comment by Morphark** [comment]
Having Same Problem. Did someone found any solution for it ?
