### ISSUE TITLE
Scan networks nearby issue

### ISSUE THREAD

**Issue by cyber-gh** [arismelachroinos/lscript#128]
When I am using scan networks nearby to capture a handshake it shows all the networks I am looking for. But as soon as I press ctr-c to stop the scan and select the desired network there is not a single network listed.

**Comment by arismelachroinos** [comment]
That was a previous issue I found and fixed. If I understood correctly, the aircrack suite was updated and lscript handshake had this issue. So the latest version 2.1.5 of lscript works well with the latest version of kali. Please do some apt upgrade and updates to get the latest kali and test again. It should fix the issues. Please report back. Thank you
