### ISSUE TITLE
Add tool

### ISSUE THREAD

**Issue by Ekultek** [arismelachroinos/lscript#13]
Add a hash cracker, preferably Dagon https://github.com/ekultek/dagon :)

**Comment by arismelachroinos** [comment]
of course!

**Comment by arismelachroinos** [comment]
i get :
python dagon.py 
Traceback (most recent call last):
  File "dagon.py", line 10, in <module>
    from bin.verify_hashes.verify import verify_hash_type
  File "/root/dagon/bin/verify_hashes/verify.py", line 5, in <module>
    from lib.settings import (
  File "/root/dagon/lib/settings.py", line 10, in <module>
    from colorlog import ColoredFormatter
ImportError: No module named colorlog

when launching the tool. If i find a fix i will include it in lscript.

**Comment by Ekultek** [comment]
Did you install the requirements?

- Thomas Perkins

**Comment by Ekultek** [comment]
Run pip install -r requirements.txt from the dagon directory

- Thomas Perkins

**Comment by arismelachroinos** [comment]
of course i did. i even installed them seperately . nothing. All are installed but it doesnt work.

**Comment by arismelachroinos** [comment]
when installing the requirements i get : 
pip install -r requirements.txt 
Requirement already satisfied: pysha3==1.0.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Collecting colorlog==2.10.0 (from -r requirements.txt (line 3))
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Requirement already satisfied: passlib==1.7.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Collecting bcrypt==3.1.3 (from -r requirements.txt (line 5))
  Using cached bcrypt-3.1.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting cffi>=1.1 (from bcrypt==3.1.3->-r requirements.txt (line 5))
  Using cached cffi-1.10.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from bcrypt==3.1.3->-r requirements.txt (line 5))
Collecting pycparser (from cffi>=1.1->bcrypt==3.1.3->-r requirements.txt (line 5))
  Using cached pycparser-2.18.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/usr/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named 'pkg_resources.extern'


I installed colorlog via apt-get as there was an error when launching. Now when i do python dagon.py -h i get : 

python dagon.py -h
Traceback (most recent call last):
  File "dagon.py", line 10, in <module>
    from bin.verify_hashes.verify import verify_hash_type
  File "/root/dagon/bin/verify_hashes/verify.py", line 5, in <module>
    from lib.settings import (
  File "/root/dagon/lib/settings.py", line 12, in <module>
    from lib.algorithms.hashing_algs import *
  File "/root/dagon/lib/algorithms/hashing_algs.py", line 8, in <module>
    import sha3
ImportError: No module named sha3

**Comment by Ekultek** [comment]
What operating system?

**Comment by Ekultek** [comment]
`"/usr/lib/python3/dist-packages/pip/req/req_install.py"` dagon runs on python 2.7.x

**Comment by arismelachroinos** [comment]
command : pip2.7 install -r requirements.txt
fixed the issue.  Will be included on the next update.

**Comment by arismelachroinos** [comment]
@Ekultek  Check the new update , got to Tools -> Others -> Dagon

**Comment by Ekultek** [comment]
Woohoo! Love it!

**Comment by arismelachroinos** [comment]
:)
