### ISSUE TITLE
Handshake option 10 dosent work

### ISSUE THREAD

**Issue by solonaro** [arismelachroinos/lscript#136]
Hello,

When I try to run Handshake it says its opening a new terminal and then just redirects me back to the menu with no terminal opened.

Thanks in advance

**Comment by solonaro** [comment]
I am guessing I don’t have it installed

When I type gnome-terminal it says command not found.

How can I install this and make it work, sorry I am  new to this.

Thank you

**Comment by arismelachroinos** [comment]
You will need to either install Kali on you pc (not recommended for daily use) or install a virtual machine and install latest full version of kali in there. VMware workstation is very good. Try watching some yt tutorials on that procedure.

**Comment by solonaro** [comment]
I already have it running on Virtual Box and I have the latest Kali.

It gives me an error like line 6884 : gnome terminal: command not found.

My terminal works fine I installed the scrip with no issue.

I appreciate your help

**Comment by solonaro** [comment]
Do you think maybe because I downloaded the Xfce version?

Which one would be best?

Thank you so much

**Comment by omaryomario** [comment]
when i typed that it gives me poped up treminal
