### ISSUE TITLE
Kali Linux problem when i type l

### ISSUE THREAD

**Issue by deadfishhackers** [arismelachroinos/lscript#144]
im using kali linux and when i type ``l`` nothing happens it only works when i type ``./l``
How to fix that?

**Comment by TN3rd** [comment]
sudo l? Or elevate with sudo su and then try tiping l

**Comment by deadfishhackers** [comment]
Thanks for replying I fixed it close the thread, I had parrot OS terminal styling on and when I turned it off it worked thanks
