### ISSUE TITLE
bash: l: command not found

### ISSUE THREAD

**Issue by Blackwolf499** [arismelachroinos/lscript#145]
Kali Linux, newest version

Running the script doesn't work

using the letter 'l' does not work either.

**Comment by igorsanchez** [comment]
I have the same problem...

**Comment by Gloffan** [comment]
a couple of times did reinstall.I run like this:
# cd lscript

**Comment by Gloffan** [comment]
Try reinstall

**Comment by basilhsk7** [comment]
same. problem
neither. reinstall didnt made any difference

**Comment by 403-Fruit** [comment]
@shall1569 That's because Parrot OS has a line in ~/.bashrc file like this:  

`alias l='ls -CF'`  

The same goes for ubuntu and probably a few other distros. You need to edit your .bashrc and either delete/change that line, or add this  

`alias x='/usr/bin/lscript'`  

Changing 'x' to whatever you want the command to be. It might be helpful to know that you can figure out what your terminal is actually resolving a command to by running  

`type -a command`  

Not sure what everyone else's issues are though because "Running the script doesn't work" doesn't really tell you much and I don't know how its possible to know that its all the same problem.

**Comment by shall1569** [comment]
> 
> 
> @shall1569 That's because Parrot OS has a line in ~/.bashrc file like this:
> 
> `alias l='ls -CF'`
> 
> The same goes for ubuntu and probably a few other distros. You need to edit your .bashrc and either delete/change that line, or add this
> 
> `alias x='/usr/bin/lscript'`
> 
> Changing 'x' to whatever you want the command to be. It might be helpful to know that you can figure out what your terminal is actually resolving a command to by running
> 
> `type -a command`
> 
> Not sure what everyone else's issues are though because "Running the script doesn't work" doesn't really tell you much and I don't know how its possible to know that its all the same problem.

Will give it a try! :)

**Comment by 403-Fruit** [comment]
@shall1569 My mistake, I believe the correct path should be '/bin/lscript/l'. I think it may be better to add the directory that contains the 'l' file to your $PATH. Replacing the alias with the following line should do it.  

    export PATH=$PATH:/bin/lscript  

Then run  

    source /etc/bashrc  

And it should work so long as /bin/lscript/l is the correct location.

**Comment by BreitlingNL** [comment]
you need to move it to your root folder 
`cp -r /home/Username/Desktop/lscript /root/`
then you need to move the scrip l in to your root folder
`cp -r /root/lscript/l /root/`
then it should work
the only thing i cant do is install tools :(

**Comment by rajesh457** [comment]
open the .bashrc file by following the command

`leafpad .bashrc
`
then search for **some more ls alisses** by Cntrl + F
then 
add this line
`alias l='usr/bin/lscript'`
then at the end of the **.bashrc** file add the following line
export PATH=$PATH:/bin/lscript
alias l='/usr/bin/lscript/l'

save the .bashrc file and it's done

**Comment by Syedmahmood777** [comment]
If you’re using Kali Linux  first install
Gnome by
`sudo apt-get  install gnome-terminal`
After the installation you should lazy script the normal way 
If the above code says error 
`E: Unable to locate package installer`
Then type
`sudo nano /etc/apt/sources.list`
And add this at the bottom
`deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali sana main non-free contrib
# deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
deb http://old.kali.org/kali moto main non-free contrib
# For source package access, uncomment the following line
# deb-src http://old.kali.org/kali moto main non-free contrib`
And save it after that write the code
`sudo apt-get install checkinstall`
Then try the first code and then install lazyscript
Credits  ourcodeworld.com
And
 tech for hack (Youtube)

**Comment by arismelachroinos** [comment]
@Blackwolf499  @igorsanchez  @basilhsk7 @403-Fruit @shall1569   To install the script, follow this tutorial: https://youtu.be/xcb5uwP5nSU

**Comment by rikkishade** [comment]
> I have the same problem...

just type 'bash l'
it will work in kali linux

**Comment by ghost** [comment]
this is what worked for me had same issue
first: cd lscript
then: sudo su to run as root
then: bash "l" that should fix it
