### ISSUE TITLE
Someone stole your script

### ISSUE THREAD

**Issue by ShawnCena121** [arismelachroinos/lscript#148]
I was browsing Instagram and I came across the hashtag Kali Linux, and I saw a post about your script. I clicked on the profile and the account is all about your script renamed to ehtools. Sorry to bother you about this. But stealing content isn't cool. There is no credibility to you. Here is the Instagram account: @ehtools_framework

**Comment by aloneesoft** [comment]
i really hope he gets terminated, probably some kid, who is trying to look cool

**Comment by arismelachroinos** [comment]
Well its not that ethical to get all the code and change the names of who made it, but hey, lscript gets 200 unique clones every day for two years now. So I guess I helped somebody with it. As of this guy, maybe it would have been better if he just started his own just like I did. I do not see the point on doing that, my code is a mess anyways so good luck with that too.

**Comment by Ekultek** [comment]
Well, it doesn’t seem like it’s going to go anywhere anytime soon, if you’re really worried about it you can complain to GitHub and see if they can do something about it. Also it’s got like 3 stars so nothing to really worry about

**Comment by entynetproject** [comment]
Hello everyone, if you do not like what I'm trying to customize your wonderful script, then I can delete your repository, and I do not understand your license says that you can distribute and modify the code, if it was patented I would not change it! Please forgive and understand, waiting for an answer!

**Comment by entynetproject** [comment]
If you want you can complain about me but I can delete my repository, besides I do not want you to think about me bad, besides I have a lot of other good projects! Please understand!

**Comment by arismelachroinos** [comment]
@entynetproject 
Hello sir,
as I saw, you claim to have build that script your own from scratch, and you demand that no one should copy your script.
As I understand by a quick look at the code, it is just a quick theme over my script. Its okay if you want to modify it and you want another theme, but the part I do not really understand is that you clearly state that your script has nothing to do with lscript and it is completely a new script, which is obviously misleading. You made a whole website and you wanted to get paid for a theme and also claim to have extra features? I did not say it is illegal or anything, but I said that this move did not show any respect at all. If you say its a wonderful script, use it, share it and if you feel happy to donate, do that, however copying it with no credit at all about where it came from, and claiming that you have coded it, was not that ethical in my opinion. It showed me that you dont care at all about the person who made it, and you just want to seem cool. That is my opinion, you can do whatever you wish. Its not on the legal part, but on the ethical part, as far as I am aware.
