### ISSUE TITLE
Ubuntu 17.04

### ISSUE THREAD

**Issue by Ekultek** [arismelachroinos/lscript#15]
`l` is shortened for `ls` and when you install the script on ubuntu, it doesn't work because it won't copy over the `l` command. I know you say this is for `kali` but there's no reason why it shouldn't work on all Linux systems.

**Comment by arismelachroinos** [comment]
it's is already reported, I made this before even knowing that could even happen. I will try to add support for others too when I have time.

**Comment by Ekultek** [comment]
Well here's the thing, it works, but `l` is not a valid command to use for it, you could use `la` or `laz`

**Comment by arismelachroinos** [comment]
yeah sure , others have reported that and i am aware of that. I will try to add an option to the installer. Did you try to install the script to Ubuntu?

**Comment by arismelachroinos** [comment]
Lscript is only for Kali. The fix is not as simple as changing the name , as inside the script , other subscripts are called, and it doesnt worth it to try to fix all the different issues , for an OS that is not designed for pentesting.

**Comment by Ekultek** [comment]
Any OS can be set up to pen test
