### ISSUE TITLE
Hello, aris, please read me!

### ISSUE THREAD

**Issue by entynetproject** [arismelachroinos/lscript#151]
Hello everyone, if you do not like what I'm trying to customize your wonderful script, then I can delete your repository, and I do not understand your license says that you can distribute and modify the code, if it was patented I would not change it! Please forgive and understand, waiting for an answer!

**Comment by arismelachroinos** [comment]
Hello sir,
as I saw, you claim to have build that script your own from scratch, and you demand that no one should copy your script.
As I understand by a quick look at the code, it is just a quick theme over my script. Its okay if you want to modify it and you want another theme, but the part I do not really understand is that you clearly state that your script has nothing to do with lscript and it is completely a new script, which is obviously misleading. You made a whole website and you wanted to get paid for a theme and also claim to have extra features? I did not say it is illegal or anything, but I said that this move did not show any respect at all. If you say its a wonderful script, use it, share it and if you feel happy to donate, do that, however copying it with no credit at all about where it came from, and claiming that you have coded it, was not that ethical in my opinion. It showed me that you dont care at all about the person who made it, and you just want to seem cool. That is my opinion, you can do whatever you wish. Its not on the legal part, but on the ethical part, as far as I am aware.

**Comment by entynetproject** [comment]
I did not say that the script was created from scratch, I realized my mistake and now the moderator is working to write on all the pages where we have indicated ourselves, your name and also a link to the original, I do not want to seem the enemy, and what about the money is my mistake, we never earned on this script, it was Sorry of course I will delete this stupid status, I didn't mean to offend you, I bagatelle indicate official source :)
