### ISSUE TITLE
Hello 👋 I am not stole your script

### ISSUE THREAD

**Issue by entynetproject** [arismelachroinos/lscript#152]
If you want you can complain about me but I can delete my repository, besides I do not want you to think about me bad, besides I have a lot of other good projects! Please understand!

**Comment by arismelachroinos** [comment]
Guys please open one issue for an issue you have. Not multiple. 
If you can code, make a script. If you cannot code, make a script as well. I did not know anything about bash before lscript. If you have a lot of other good projects, I would focus on that and not disrespect the scripts I can wonderful.
