### ISSUE TITLE
Cannot run with l command. an alias is assigned to l to = ls.  I deleted it from the bash but when I us root it seems to be active again.

### ISSUE THREAD

**Issue by BigRatter** [arismelachroinos/lscript#166]

**Comment by arismelachroinos** [comment]
What is your OS sir...

**Comment by BigRatter** [comment]
Ubuntu 18x

**Comment by BigRatter** [comment]
I don't know enough to chat intelligently about the problem.  Sorry I will try though

**Comment by arismelachroinos** [comment]
No it is okay. It is only designed for Kali Linux. It is written in the instructions.

**Comment by BigRatter** [comment]
Ok, thank you for your time! Much appreciated
