### ISSUE TITLE
lscript

### ISSUE THREAD

**Issue by DarthLordMeilodaz** [arismelachroinos/lscript#170]
Hello,

Yes, I know this program is for Kail Linux, but I have Lazy installed on Parrot OS, it works fine until I try going back to the main screen " bash: ./l: No such file or directory " keeps popping up. I am trying to figure out the command codes to fix this issue, but I am not having any luck.

**Comment by iftikharasif142** [comment]
yes not working

**Comment by iftikharasif142** [comment]
showing that you not enter yes
