### ISSUE TITLE
Monitor mode not working

### ISSUE THREAD

**Issue by ASOwnerYT** [arismelachroinos/lscript#174]
When I try to run a tool that needs monitor mode enabled, it asks me to enable monitor mode even if it is already enabled. And when I press 'y' to enable monitor mode, it doesn't enable it and just keeps on asking me to enable it.

**Comment by arismelachroinos** [comment]
Not sure about that. On the main lscript screen, type `stop` to exit monitor mode, and then type `start` to enable it.

**Comment by ASOwnerYT** [comment]
I made that ages ago. It was probably because my wifi card doesn't support monitor mode. Thanks anyway.

**Comment by JustVladKaz** [comment]
HERE IS SOLUTION: https://github.com/arismelachroinos/lscript/issues/309#issue-888053128
