### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by hissro** [arismelachroinos/lscript#175]
hello ,, 

> Press any key to go back...

bash: ./l: No such file or directory
┌─[✗]─[root@ssM]─[~/lscript]
└──╼ #./l
> 

script cant go back after press any key ,  and when im trying lunch script by type (l)  on terminal  not working , can i have help about this

**Comment by arismelachroinos** [comment]
Did you install the script on Kali Linux?

**Comment by yako127** [comment]
hi 
can you explain me this please "./install.sh: line 109: gnome-terminal : command not found"

**Comment by arismelachroinos** [comment]
apt-get install -y gnome-terminal

**Comment by yako127** [comment]
> apt-get install -y gnome-terminal

THANK YOU SO MUCH YOU HELPED ME SOLVE MY PROBLEM

**Comment by canelesso** [comment]
I get the same error on install "./install.sh: line 111: gnome-terminal: comand not found"
I tryied "apt-get install -y gnome-terminal" but can't find the package gnome-terminal....any help?
Thanks in advace!

**Comment by yako127** [comment]
hi
did you resolve your issue.

**Comment by canelesso** [comment]
yes i did! the problem was the root user.....thanks!

Il giorno sab 18 apr 2020 alle ore 17:00 yako127 <notifications@github.com>
ha scritto:

**Comment by yako127** [comment]
great!

**Comment by arismelachroinos** [comment]
@hissro @canelesso To install the script, follow this tutorial https://youtu.be/xcb5uwP5nSU

**Comment by PenTester-lab-sys** [comment]
im on mac and i got the ./install.sh: line 111: gnome-terminal: command not found error can anyone help plz.

**Comment by yako127** [comment]
hi
you need to install gnome-terminal

**Comment by tushar-003** [comment]
> Did you install the script on Kali Linux?

can I install it in cloud shell?

**Comment by AniChan21** [comment]
./install.sh: line 111: gnome-terminal: command not found
what to do man?
