### ISSUE TITLE
unable to install tools or there are install errors please help

### ISSUE THREAD

**Issue by Dinu777** [arismelachroinos/lscript#177]

**Comment by CoffeeNData** [comment]
I have the same problem.

**Comment by tcabral1** [comment]
-e Are you updating or installing the script?(u/i): 
-e Only use 'i' for the first time.

when i type in i the screen come again...

**Comment by arismelachroinos** [comment]
@Dinu777  @CoffeeNData  @tcabral1  To install the script on Kali Linux 2020.2 follow this tutorial: https://youtu.be/xcb5uwP5nSU
