### ISSUE TITLE
New terminal window

### ISSUE THREAD

**Issue by jon0881** [arismelachroinos/lscript#179]
Hi,

Ive got the Kali image running on a PiZero W. loving the simplicity of the script but the main issue i have is when the script is popping a new gnome terminal. Im using Putty with SSH to get into the Pi via the usbEth so i can use the wlan for monitor mode. When trying to pop a new terminal its not working as its trying gnome in a full Linux gui.

Ive tried to install gnome-terminal with xming on the W10/Putty machine but it didnt work either. 
Does anyone have any other suggestions?

/Jon

**Comment by arismelachroinos** [comment]
Sorry, I have no fix for that. 
To open the handshake window directly you can type `lh1` but again, there are other gnome-terminal windows that need to open for the handshake, so no.
