### ISSUE TITLE
I would appreciate some help. Thanks

### ISSUE THREAD

**Issue by alfdav** [arismelachroinos/lscript#18]
This happens after running the ./install.sh 

Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Terminal received signal 11
Killed

**Comment by arismelachroinos** [comment]
are you using kali? and is this the first thing you see after you type. /install.sh?

**Comment by alfdav** [comment]
Yes, to both questions.

**Comment by Ekultek** [comment]
This has nothing to do with `lscript` it's your operating system, try Google
