### ISSUE TITLE
"Not enough disk space"

### ISSUE THREAD

**Issue by Anonym9999** [arismelachroinos/lscript#181]
Hello everybody, 
today I have cloned the lscript for my Kali linux machine. 
Everything worked out great, but after I installed tools, my terminal had "not enough space". 
I thought that was a joke, but it was not. When I looked up how much space I had left, I was surprised. 0 kilobytes / 25GB. It can only be due to the lscript, because I uninstalled it nacher and then suddenly again 8 GB were free. I'm very sure that if I clone it, it would not be that many GBs. 
Could someone help me please? 
Greetings Tobi

**Comment by arismelachroinos** [comment]
The lscript is not even half a megabyte. Pay attention to what other tools you are installing.
