### ISSUE TITLE
Lazy scrip doesnt find any networks nearby...

### ISSUE THREAD

**Issue by indulonajones** [arismelachroinos/lscript#184]
Lazy scrip doesnt find any networks nearby... I can see networks in default wifi list but not when i let´s say try handhake it just says no networks nearby. I have kali just on virtual box, just saying...

**Comment by arismelachroinos** [comment]
@indulonajones  what version of Kali do you have?

**Comment by arismelachroinos** [comment]
Reopen if there is an issue.
