### ISSUE TITLE
Moving to new terminal...

### ISSUE THREAD

**Issue by tuxjunkie** [arismelachroinos/lscript#187]
/bin/lscript/l: line 6884: gnome-terminal: command not found
Happens in Mate Terminal, XTerm and Qterm
Closes and goes back to Lazy main screen.

Kali 2019.4 - Mate Desktop, marco

**Comment by arismelachroinos** [comment]
apt-get install gnome-terminal
?

**Comment by tuxjunkie** [comment]
I did have gnome-terminal installed, but removing and reinstalling it seems to have resolved it. I should have updated GIT. Thanks for your reply.
