### ISSUE TITLE
lzy not  open

### ISSUE THREAD

**Issue by kaal-kali** [arismelachroinos/lscript#190]
the blank terminal is opening after pressing l key

**Comment by arismelachroinos** [comment]
apt-get install gnome-terminal
?

**Comment by hackvice** [comment]
same here, nothing happens after i press l

**Comment by arismelachroinos** [comment]
> same here, nothing happens after i press l

What do you mean nothing happens? Post a screenshot. If you don't give me details I cannot fix it. Are you using Kali Linux?

**Comment by nicolasfritzges** [comment]
![Captura de pantalla_2019-12-15_12-46-52](https://user-images.githubusercontent.com/27820946/70865155-096da900-1f39-11ea-8cdf-9d9733894bba.png)
same issue

**Comment by arismelachroinos** [comment]
Open a new terminal and type `ifconfig`. Does this command work? If you get a black screen it should have to do with your wireless adapter. Unplug it, plug it, and retry.
Report back.

**Comment by CoffeeNData** [comment]
Not the same for me, when I write 'l' to open lscript, it prompts 'bash: l: command not found'.

**Comment by Dinu777** [comment]
it is not working for xfce pls do something for that

**Comment by arismelachroinos** [comment]
@Dinu777  What do you mean it is not working? Explain your problem if you want if fixed. What error do you get and what kali are you running?

**Comment by Dinu777** [comment]
sorry for that I just saw the version number of mine got it updated its working fine
thank you
