### ISSUE TITLE
Could not find the database of available applications, run update-command-not-found as root to fix this

### ISSUE THREAD

**Issue by hemanthkumar98** [arismelachroinos/lscript#195]
root@kali:~/Desktop/lscript# l
Could not find the database of available applications, run update-command-not-found as root to fix this
Sorry, command-not-found has crashed! Please file a bug report at:
http://www.debian.org/Bugs/Reporting
Please include the following information with the report:

command-not-found version: 0.3
Python version: 3.7.5 final 0
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2019.4
Codename:       kali-rolling
Exception information:

local variable 'cnf' referenced before assignment
Traceback (most recent call last):
  File "/usr/share/command-not-found/CommandNotFound/util.py", line 23, in crash_guard
    callback()
  File "/usr/lib/command-not-found", line 93, in main
    if not cnf.advise(args[0], options.ignore_installed) and not options.no_failure_msg:
UnboundLocalError: local variable 'cnf' referenced before assignment
root@kali:~/Desktop/lscript#

**Comment by AbdElraoufSabri** [comment]
1. edit `/etc/apt/sources.list` and change 

> deb http://http.kali.org/kali kali-rolling main non-free contrib

to 

> deb https://http.kali.org/kali kali-rolling main non-free contrib

**NOTE** https

1. run `sudo apt update`

1. run `sudo update-command-not-found`

**Comment by arismelachroinos** [comment]
@hemanthkumar98  @AbdElraoufSabri  Follow this tutorial to install the script: https://youtu.be/xcb5uwP5nSU
