### ISSUE TITLE
issue while installing , plz help soon

### ISSUE THREAD

**Issue by gpssahaj** [arismelachroinos/lscript#199]
Open a NEW terminal and type 'l' to launch the script,
l is not working in the new terminal.

**Comment by arismelachroinos** [comment]
What system what version what terminal

**Comment by gpssahaj** [comment]
Parrot os
Security
Mate terminal 1.22.1

**Comment by gpssahaj** [comment]
![lscript](https://user-images.githubusercontent.com/59232551/71731359-86ba7880-2e6a-11ea-801a-121339f4a043.png)

**Comment by arismelachroinos** [comment]
Not supported. Read the instructions before posting an issue.
