### ISSUE TITLE
Installing prblm

### ISSUE THREAD

**Issue by PhilippeLeHacker** [arismelachroinos/lscript#200]
I'm on Kali Linux and evrything went good during the installation until the YES/NO question about my own responsability where if i write YES, I have a permission denied on the Iagree.txt that i can't find anywhere. I'm a beginner, sorry if it's a little problem but I really need help :)

**Comment by arismelachroinos** [comment]
Are you signed in as a root user? 
![image](https://user-images.githubusercontent.com/21193898/72149961-0e454180-33ad-11ea-969c-195ff972bc27.png)

**Comment by PhilippeLeHacker** [comment]
For an unknown reason, I can't (i'm on a usb bootable and the root session with toor as password does not work, and i can't sudo -i cause it open a new terminal

**Comment by arismelachroinos** [comment]
I am sorry this is not relevant to the script

**Comment by Bluesherlock** [comment]
but even when on root, when i type "l" . it says command not found
