### ISSUE TITLE
Wifite Issue

### ISSUE THREAD

**Issue by jabod1** [arismelachroinos/lscript#201]
It is definitely installed but lscript keeps telling me that it is not installed and that I need to type install to install it. SO I typed install, went back and it is still telling me that it is not installed.

**Comment by arismelachroinos** [comment]
On what menu are you sir? Where does this issue appear?

**Comment by jabod1** [comment]
under Wifi Tools
so I type l to start lscript then 9 for TOOLS and then 1 for Wifi Tools and wifite is still red

**Comment by arismelachroinos** [comment]
Please uninstall the script and re-install it. I just updated the script, tell me if it worked (i did not change the version of the script so you cannot just press update. You have to reinstall)

**Comment by jabod1** [comment]
THat worked. Thank you very much!
