### ISSUE TITLE
Wifite issues

### ISSUE THREAD

**Issue by plasteconcracks** [arismelachroinos/lscript#202]
i installed the script and followed all the steps but i get this error message
/bin/lscript/l: line 3139: conditional binary operator expected
/bin/lscript/l: line 3139: syntax error near `wifite'
/bin/lscript/l: line 3139: `    if [[ which wifite ]]'

**Comment by plasteconcracks** [comment]
also i have updated it and this error came up 
./install.sh: line 109: gnome-terminal: command not found

**Comment by arismelachroinos** [comment]
Sorry for that, just fixed it, try again.

**Comment by arismelachroinos** [comment]
to fix the gnome-terminal error, type `apt-get install -y gnome-terminal` in a new terminal

**Comment by plasteconcracks** [comment]
I tried apt-get install -y gnome-terminal in a new terminal and then updated it no errors popped up after the update but still if I type l in a new terminal this error still comes up.

/bin/lscript/l: line 3139: conditional binary operator expected
/bin/lscript/l: line 3139: syntax error near wifite' /bin/lscript/l: line 3139: if [[ which wifite ]]'

**Comment by arismelachroinos** [comment]
Delete the script and clone again from github and install again. The issue has been fixed.
