### ISSUE TITLE
AGREE.txt permissions not sufficient after agreeing to terms

### ISSUE THREAD

**Issue by nixbys** [arismelachroinos/lscript#204]
When trying to agree to the terms so I can use the tool it refuses to run due to insufficient permissions and just closes. It opens the AGREE.txt file and tries to read from that however the file is not present in install or on this repository at time of writing. If I am missing something please feel free to help guide and troubleshoout the problem until it works. Thanks in advance!

**Comment by arismelachroinos** [comment]
Are you using Kali Linux? Are you a root user?

**Comment by joshua-darby** [comment]
Yes I am to answer both questions.

**Comment by arismelachroinos** [comment]
The file AGREE.txt is not in the repository. It is created when you agree to the terms. 
Do you have the lscript folder in /root or in Desktop? Did you follow the installation instructions?
