### ISSUE TITLE
Not installing on Kali Linux 2019.4 64bits

### ISSUE THREAD

**Issue by CoffeeNData** [arismelachroinos/lscript#205]
It just does not install.
```
./install.sh: line 109: gnome-terminal: command not found
```

**Comment by CoffeeNData** [comment]
I have tried to run in the gnome-terminal. It doesn't work.
It throws a bunch of errors

**Comment by arismelachroinos** [comment]
No you haven't tried. You don't have gnome terminal.search the previous issues.
