### ISSUE TITLE
bash: :no file or directory

### ISSUE THREAD

**Issue by Antibionick** [arismelachroinos/lscript#207]
When I start lscript is working, but when I won't to go back (Push b to go back), it tells me: > bash: :no file or directory . What can I do???

**Comment by arismelachroinos** [comment]
Before posting an issue please check if it is already posted.

**Comment by Antibionick** [comment]
@arismelachroinos I have kali, and it still doesnt work. what is the Problem?

**Comment by arismelachroinos** [comment]
Uninstall, remove lscript folder and re clone from GitHub and reinstall
