### ISSUE TITLE
./install.sh: line 109: gnome-terminal: command not found

### ISSUE THREAD

**Issue by luke110206** [arismelachroinos/lscript#209]
**Describe the bug**
Unable to install on virtual box machine

**To Reproduce**
1. Get a virtual box version of kali.
2. go though the setup normally
3. At install watch closely it says it then at the end it stops at it
4. ERROR: ./install.sh: line 109: gnome-terminal: command not found

**Expected behavior**
I expected at installation complete message

**Comment by arismelachroinos** [comment]
Hello sir thank you for reporting. To fix the issue open can you terminal and type `apt-get install -y gnome-terminal`

**Comment by arismelachroinos** [comment]
I will include this fix in the install file soon

**Comment by luke110206** [comment]
I got an error saying permission denied but I realized I had to use sudo after rerunning with sudo it says unable to locate package gnome-terminal

**Comment by arismelachroinos** [comment]
If you're in the install instructions, you will see that you need to be a root user to run the script

**Comment by luke110206** [comment]
Can I use sudo -i because the root user seems to be disabled on this install

**Comment by luke110206** [comment]
I got it working
