### ISSUE TITLE
Wont work via SSH, Windows 10 Kali linux, or (from my experience) anything other than gnome

### ISSUE THREAD

**Issue by ASOwnerYT** [arismelachroinos/lscript#217]
**Describe the bug**
It installs, seems to install correctly, but when I try typing 'l' into a different terminal window like it says, it doesn't detect it as a command

**To Reproduce**
1. Install, with the terminal, following the instructions on the github 'readme.md'

**Expected behavior**
To work normally, like I see in youtube videos.

**Screenshots**
Probably not needed. Uninstalled before I took screenshots sorry.

**Output of `cat /etc/os-release`**
Uninstalled before I did this. Please tell me if this would of helped, sorry.

**Output of `whoami`**
Uninstalled before I did this. Please tell me if this would of helped, sorry.

**Additional context**
Nah

**Comment by arismelachroinos** [comment]
Hello sir, I never said that it works on anything other than Kali Linux. Also all the info you skipped reporting are needed.

**Comment by ASOwnerYT** [comment]
Running it on Kali Linux is exactly what I am trying to do! This is frustrating because the new installer installs xfce desktop environment by default rather than gnome. Maybe a better title for this issue would be 'Please update it to work with newest version of Kali Linux'.
