### ISSUE TITLE
Support for kali linux kde environment

### ISSUE THREAD

**Issue by Dinu777** [arismelachroinos/lscript#218]
I had been using the tool when i had gnome xfce but now i have shifted to kde which is not supported can you make the necessary change for it to support kde environment

**Comment by Yousaf-Babur** [comment]
I am having the same problem.The script was working fine but when i switched from GNOME to kde.The script does not work.I would request @arismelachroinos  to add support for Kali Linux KDE desktop environment support for Lazy Script.
Thanks in Advance

**Comment by arismelachroinos** [comment]
@Yousaf-Babur  @Dinu777  To install the script on Kali Linux 2020.5 follow this tutorial: https://youtu.be/xcb5uwP5nSU

**Comment by Yousaf-Babur** [comment]
Thanks @arismelachroinos
