### ISSUE TITLE
Not allowing me to accept terms 

### ISSUE THREAD

**Issue by bentflur** [arismelachroinos/lscript#219]
When I have done installing the scripts it opens to a new terminal and tells me to accept the terms and conditions to accept I have to type 'YES' when I type yes, or YES, or Y either one it always says "You didn't type 'YES' , So you can not continue. 

When you finish all the steps to install it, it will ask you to type l to continue. It says you need to accept the terms.

Its supposed to allow me to accept the terms but it won

**Screenshots**
https://prnt.sc/rig3z8
https://prnt.sc/rig528
https://prnt.sc/rig5om

**Comment by arismelachroinos** [comment]
Type it in capitals......

**Comment by we-script** [comment]
he literally just said he did it in capitals, non capitals and just Y
