### ISSUE TITLE
Nothing showing up when opening Lazy Script

### ISSUE THREAD

**Issue by bentflur** [arismelachroinos/lscript#220]
After opening Lazy Script nothing pops up in the terminal, here is what I mean

https://prnt.sc/ril7ye

**Comment by arismelachroinos** [comment]
Something is wrong with your interfaces. Reinsert you wireless antenna

**Comment by bentflur** [comment]
what do u mean by wireless antenna?

**Comment by arismelachroinos** [comment]
Try restarting your system. Also try `ifconfig` on a terminal to see if it loads.

**Comment by arismelachroinos** [comment]
When lscript launches, the command `ifconfig` is being launched as well to determine your wireless interfaces. If you have any issues with your wireless interfaces then it stucks there.

**Comment by arismelachroinos** [comment]
No response
