### ISSUE TITLE
Install Failure 

### ISSUE THREAD

**Issue by LatyrGitHub** [arismelachroinos/lscript#228]
Hello

An error message at the end of installation process, script does not work. 

**To Reproduce**
As a root user, I have executed, on an update latest version of Kali Linux amd64:
```
cd
git clone https://github.com/arismelachroinos/lscript.git
cd lscript
chmod +x install.sh
./install.sh
```
It ends with error message:

> Open a NEW terminal and type 'l' to launch the script
> Unable to init server: Could not connect: Connection refused
> # Failed to parse arguments: Cannot open display:

**Expected behavior**
'l' or './l' at minimum from the 'lscript' dir should run the script but it does not.

**Output of `cat /etc/os-release`**
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.2"
VERSION_ID="2020.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Output of `whoami`**
root

**Comment by arismelachroinos** [comment]
Hi,

it seems you have an issue with your display setting.

What is the output of the command 'echo $DISPLAY'?

**Comment by LatyrGitHub** [comment]
> Hi,
> 
> it seems you have an issue with your display setting.
> 
> What is the output of the command 'echo $DISPLAY'?

With root, the line below is empty.

**Comment by arismelachroinos** [comment]
Are you using ssh? Or do you use a graphical interface? Lscript needs GUI and cannot be run without it. It has to open multiple terminal windows.

**Comment by arismelachroinos** [comment]
what is the output of the command `gnome-terminal`? I am pretty sure you are not using a graphical interface and that is the issue

**Comment by LatyrGitHub** [comment]
Hello

Execute from terninal window launched from the GUI. The graphical environment is Xfce (Default Environnent) as per https://www.kali.org/releases/kali-linux-2020-1-release/

> root@kali:~# gnome-terminal
> Unable to init server: Could not connect: Connection refused
> # Failed to parse arguments: Cannot open display: 
> root@kali:~# 
>

**Comment by arismelachroinos** [comment]
What is the output of `cat /etc/ssh/sshd_config | grep "X11Forwarding"`?

**Comment by arismelachroinos** [comment]
Maybe try `export DISPLAY=:0.0`

**Comment by LatyrGitHub** [comment]
> What is the output of `cat /etc/ssh/sshd_config | grep "X11Forwarding"`?

cat /etc/ssh/sshd_config | grep "X11Forwarding"
X11Forwarding yes
#       X11Forwarding no

**Comment by LatyrGitHub** [comment]
> Maybe try `export DISPLAY=:0.0`

No result. Empty

**Comment by LatyrGitHub** [comment]
> Hi
> 
> I may have found the issue.
> https://www.kali.org/releases/kali-linux-2020-1a-release/
> 
> Reinstalling the VM now

VM reinstall from scratch and still the same error message

**Comment by LatyrGitHub** [comment]
Hello

From what I see, I am not the only one having issues.

[](https://github.com/arismelachroinos/lscript/issues/232)
[](https://github.com/arismelachroinos/lscript/issues/230)

Any chance to have more infor;ation from you.
Thanks in advance.

**Comment by LatyrGitHub** [comment]
Did a new install, cant say with, it worked

**Comment by Flare76** [comment]
> What is the output of `cat /etc/ssh/sshd_config | grep "X11Forwarding"`?

i have the same problem and it tells me 
X11Forwarding yes
#       X11Forwarding no
