### ISSUE TITLE
There was an error creating the child process for this terminal

### ISSUE THREAD

**Issue by Mouad67** [arismelachroinos/lscript#229]
There was an error creating the child process for this terminal
Failed to execute child process “bash /root/lscript/install.sh” (No such file or directory)
pleas help

**Comment by OMARx420** [comment]
did u fixed it?

**Comment by Mouad67** [comment]
Yep, thank you for your time

**Comment by OMARx420** [comment]
Can you please tell me how?

**Comment by Mouad67** [comment]
Just acce in root user
