### ISSUE TITLE
line 111: gnome terminal: command not found. 

### ISSUE THREAD

**Issue by PoisonSumu** [arismelachroinos/lscript#230]
i cant run lscript but typing l on the terminal

**Comment by OMARx420** [comment]
did u fixed it?

**Comment by davideser** [comment]
I have the same error

**Comment by barhouum7** [comment]
Try upgrading the Linux distribution you're working on. It's working fine for me on kali linux

**Comment by LatyrGitHub** [comment]
> Try upgrading the Linux distribution you're working on. It's working fine for me on kali linux

Good news may be you can be more specific as I am running the latest version
#228 and #232

**Comment by d4mz3y** [comment]
I'm having same problem here too, despite the fact I'm running the latest kali Linux

**Comment by OMARx420** [comment]
If you use the eoot user the problem will be solved.

**Comment by barhouum7** [comment]
> > Try upgrading the Linux distribution you're working on. It's working fine for me on kali linux
> 
> Good news may be you can be more specific as I am running the latest version
> #228 and #232

If you update the script is this issue still?

**Comment by arismelachroinos** [comment]
@barhouum7 @OMARx420 @d4mz3y @LatyrGitHub @davideser @PoisonSumu 
I have made a tutorial that explains how to install it on the latest version:
https://youtu.be/xcb5uwP5nSU
