### ISSUE TITLE
Error creating the child process

### ISSUE THREAD

**Issue by d4mz3y** [arismelachroinos/lscript#233]
I keep getting this error everytime I try to reinstall lazy script 

Failed to execute child process "bash /root/lscript/-install.sh" (No such file or directory) 

Can someone please help with this?

**Comment by michas492** [comment]
1. be root user
2 to need uninstall.   
How to uninstall
cd /root/lscript
./uninstall.sh
rmdir -r /root/lscript 
3. reinstall lazy script
cd git clone https://github.com/arismelachroinos/lscript.git
cd lscript
chmod +x install.sh
./install.sh

**Comment by darkt1981** [comment]
Did have it running the first time, but kept giving the IAGREE.txt error (permission denied) tried to add the text to it by hand still no luck keep telling the permissions are denied, so reinstalled and now stuck on this weird error.
- Uninstalled
- Deleted the the folder and files redownloaded

keeps saying: didnt follow the instructions. then when asked to update or install fixing now.
Select I seeing i remove the last one, keep saying I SAID ONLY ONES MSG. continues to install then 

Also tried selecting U gave me the same error and typing L in new terminal doesnt work anymore.

Keep getting:
# Error: Failed to execute child process “l” (No such file or directory)

running latest Kali 2020-1B x64 version.

**Comment by taj0023** [comment]
so everytime i should go "sudo su"??????

**Comment by arismelachroinos** [comment]
@taj0023  You must be a root user. So no, you should not do `sudo su` 
@darkt1981  You need to be in /root/ directory and clone the lscript in order for it to work properly. It is in the instructions. If you clone in Desktop then it won't work.

**Comment by arismelachroinos** [comment]
@taj0023 @darkt1981 @d4mz3y @michas492 
To install the script follow this tutorial: https://youtu.be/xcb5uwP5nSU
