### ISSUE TITLE
i have a problem when runing the file

### ISSUE THREAD

**Issue by noonessenpa1** [arismelachroinos/lscript#235]
**Describe the bug**
so when the instalation is compete it says to "open a NEW terminal type 'l' to lunch the script"
when i do it says "bash: l: command not found" and and then i tried to type something in the same terminal and this happens "Open a NEW terminal and type 'l' to launch the script
Unable to init server: Could not connect: Connection refused
# Failed to parse arguments: Cannot open display:"
**To Reproduce**
1. type in cd /opt
2. type in "git clone *github clonr link*"
3. wait until it is done
4. it will ask if tou are instaling or updating,  type in anything i had the same result in both (just when instaling it the second time it says that it shal be instaled only the first time)
5. it will say "DONE" and then "open a NEW terminal type 'l' to lunch the script"
6. the error happens

**Expected behavior**
im preety sure it shall just start the lazy script

**Output of `cat /etc/os-release`**
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.1"
VERSION_ID="2020.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
**Output of `whoami`**
root

**Additional context**
im using kali from the oficial  microsoft store

**Comment by arismelachroinos** [comment]
what is the output of `echo $DISPLAY` ?

**Comment by noonessenpa1** [comment]
nothing actualy

screenshot:
https://user-images.githubusercontent.com/64846539/81538195-b58fb080-936e-11ea-89e4-ad9754f364b0.JPG

**Comment by arismelachroinos** [comment]
Duplicate https://github.com/arismelachroinos/lscript/issues/228

**Comment by noonessenpa1** [comment]
uhh i cant,becouse im am not using a VM , im using jkali linux from the oficial microsoft store,with linux subsystem, i tried seting up a vm but for some reason it wont work.
is there any other fix?
