### ISSUE TITLE
Lazy script wont run

### ISSUE THREAD

**Issue by labbank** [arismelachroinos/lscript#237]
I had installed lazy script on parrot it was working fine. When i had closed the terminal and try and and input l to run lazyscript the command functions as if i am typing ls. So i switch to su and and go the directory to which is was downloaded to run it from there but it runs the installation sequence which it doesnt allow me to re-install. i dont know what to do.

**Comment by Ethanjc56** [comment]
I think I have this problem as well, I open the terminal and type in 'l' and it seems to think I'm typing in 'ls' the only way to get it to run is to uninstall and reinstall again.

**Comment by TsgabiXD** [comment]
> I think I have this problem as well, I open the terminal and type in 'l' and it seems to think I'm typing in 'ls' the only way to get it to run is to uninstall and reinstall again.

me too

**Comment by arismelachroinos** [comment]
@labbank @Ethanjc56 @TsgabiXD 
The Lazy Script is made for Kali Linux. To install it follow this tutorial https://youtu.be/xcb5uwP5nSU

**Comment by sachinjn** [comment]
@arismelachroinos i am facing the same issue in Kali linux. Also there is another error too - Child process not found

**Comment by massXaccel** [comment]
I am also facing the same issue. I recently installed lscript from this site using the video above on an recently updated kali Linux. I type "l" and it outputs as if i am typing "ls". There is a difference however between the 2 commands. "l" shows the contents but with forward slashes whereas "ls" does not have any forward slashes. Hope that helps
