### ISSUE TITLE
When I going through the installation is says: Type "l" to start the lazy script.... but then I get ./install.sh: line 111: gnome-terminal: command not found  PLEASE HELP

### ISSUE THREAD

**Issue by yoyonaib** [arismelachroinos/lscript#238]
When I going through the installation is says: Type "l" to start the lazy script.... but then I get ./install.sh: line 111: gnome-terminal: command not found  PLEASE HELP

**Comment by sidra67** [comment]
I have this too, what's the solution

**Comment by arismelachroinos** [comment]
@yoyonaib Follow this tutorial https://youtu.be/xcb5uwP5nSU
