### ISSUE TITLE
Unable to init server: Could not connect: Connection refused error after installation

### ISSUE THREAD

**Issue by salvador-droid** [arismelachroinos/lscript#239]
**Describe the bug**
**Note: I am running Kali Linux from the Windows 10 store**
Note: I DID run it as an administrator, I, of course, googled the problem but nothing related came up
After I run ./install.sh everything seems normal and it tells me to open a new terminal to run ls, but after a few seconds I get the following error (Image):

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Kali Linux terminal
2. log in to root user
3. cd, clone repository, cd lscript, chmod +x install.sh, ./install.sh (This all works as intended)
4. Press key to continue (it says "fixing permissions")
5. Press u/i (I tried both multiple times)
6. Error appears

**Expected behaviour**
I am able to open a new terminal, press l and it should work, however it says it can't find that command

**Screenshots**
![plshelp](https://user-images.githubusercontent.com/65813330/82731342-69e1ed00-9d06-11ea-8df6-74f64451ec45.PNG)

**Output**
Unable to init server: Could not connect: Connection refused
# Failed to parse arguments: Cannot open display:

**Comment by arismelachroinos** [comment]
To install the script, follow this tutorial https://youtu.be/xcb5uwP5nSU

**Comment by siddharthLama** [comment]
Unable to init server: Could not connect: Connection refused
# Failed to parse arguments: Cannot open display:,
 pls help me with this

**Comment by arismelachroinos** [comment]
Are you using a VM or did you download it from the Windows Store? You need to install it on a VM or on a normal drive. I think that it doesnt work if you download it from the Windows Store.
