### ISSUE TITLE
Doesn't work with linux mint 18.2 (KDE)

### ISSUE THREAD

**Issue by akshatah33** [arismelachroinos/lscript#24]
### 1. There is no gnome-terminal :
Even if I changed gnome terminal to konsole, still there are a lot of problems.
### 2. There is already a working bash command with l (ls shortcut) :  
This is the biggest problem and as l is already taken, even after changing it to another keyword (lsh), there are several problems !

**Comment by arismelachroinos** [comment]
well, it doesn't work mainly because it is only for kali, because that's what I only have. So this is not an issue. Gnome terminal is everywhere on the script, and it cannot be changed so sorry.
