### ISSUE TITLE
error 6572 agree.txt not found

### ISSUE THREAD

**Issue by FatKappa** [arismelachroinos/lscript#240]
**Describe the bug**
After i install the script i open a new terminal -> sudo su -> bash l, and after that i see the agree interface with YES/NO...immediately after writing YES an error shows error 6572 IAgree.txt no such file or directory
**Screenshots**
![photo_2020-06-01_11-29-22](https://user-images.githubusercontent.com/59336336/83390835-3cc6c600-a3fb-11ea-9c74-fbaa6a2436a3.jpg)

**Comment by arismelachroinos** [comment]
Are you a root user?..

**Comment by FatKappa** [comment]
Yeah i used sudo su and it does the same thing

**Comment by arismelachroinos** [comment]
What is the output of 'whoami'

**Comment by FatKappa** [comment]
root

**Comment by FatKappa** [comment]
i reinstalled it as the root user and it works...thx for ur support...i
thought u only need to open it as the root user..

**Comment by arismelachroinos** [comment]
Oh okay glad it worked
