### ISSUE TITLE
Not recognizeing monitor mode when enabled

### ISSUE THREAD

**Issue by cardone86** [arismelachroinos/lscript#241]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Output of `cat /etc/os-release`**
Paste the output here.

**Output of `whoami`**
Paste the output here.

**Additional context**

**Comment by JustVladKaz** [comment]
HERE IS SOLUTION: https://github.com/arismelachroinos/lscript/issues/309#issue-888053128
