### ISSUE TITLE
Not recognizeing monitor mode

### ISSUE THREAD

**Issue by cardone86** [arismelachroinos/lscript#242]
So this happens anytime I start a script out of lazy script that requires monitor mode. the latest example however is 11) Find WPS pin. I type 11 and it states monitor mode is not enabled. would you like to enable now? So of course I say "yes" then it goes through the process. once complete, instead of moving on to the next step it repeats over and over. monitor mode is not enabled, would you like to enable now? I've checked with iwconfig and it IS enabled. is there a fix or bypass for this?
![1](https://user-images.githubusercontent.com/66162878/83504219-3df70200-a492-11ea-8235-3e30f256106d.jpg)

**Comment by arismelachroinos** [comment]
Give me the output of 
ifconfig
(Make sure you are on monitor mode first)

**Comment by arismelachroinos** [comment]
No response

**Comment by JustVladKaz** [comment]
the same problem

**Comment by JustVladKaz** [comment]
HERE IS SOLUTION: https://github.com/arismelachroinos/lscript/issues/309#issue-888053128
