### ISSUE TITLE
lazy script doesnt install properly

### ISSUE THREAD

**Issue by marn20** [arismelachroinos/lscript#243]
i ran the installation commands on github.
at the end it tells to open a new terminal window and type "l". but before i can open a new window it says:
./install.sh: line 111: gnome-terminal: command not found

the new window with the "l" command says:
bash: l: command not found

i am on the latest kali linux 2020 at time of writing. For Raspberry Pi.

**Comment by arismelachroinos** [comment]
You should first do `apt-get update` in order to install packages...

**Comment by arismelachroinos** [comment]
@marn20 Here is a tutorial https://youtu.be/xcb5uwP5nSU
