### ISSUE TITLE
./install.sh: line 111: gnome-terminal: command not found

### ISSUE THREAD

**Issue by sidra67** [arismelachroinos/lscript#244]
When I was installing it, i was greeted with 
'Open a NEW terminal and type 'l' to launch the script'
./install.sh: line 111: gnome-terminal: command not found
not sure what i did wrong, even watched a tutorial on it just to make sure was still stuck here.

**Comment by arismelachroinos** [comment]
Try 
apt-get -y install gnome-terminal
