### ISSUE TITLE
Permission denied issue

### ISSUE THREAD

**Issue by JSIM9851** [arismelachroinos/lscript#245]
**Describe the bug**
Issue here:
     https://github.com/arismelachroinos/lscript/issues/243
can be fixed with sudo however once installed

# First issue instantly is:
kali@kali:~$ l
mkdir: cannot create directory '/rot/lscript/ks': permission denied
mkdir: cannot create directory '/rot/lscript/ks/nums': permission denied
# Second issue:
You need to accept the terms.
press any key to continue...
/*ENTER*/
This tool is only for educational ... with your own resposibility(YES/NO):
/YES/
/bin/lscript/l: line 6572: /root/lscript/IAGREE.txt: Permission denied

**Comment by arismelachroinos** [comment]
Please read the instructions. You must be a root user.
