### ISSUE TITLE
Wifite not opening in lazy script

### ISSUE THREAD

**Issue by Tempest3756** [arismelachroinos/lscript#248]
My main concerns are the install hcxdumptools I have the file on my desktop. Will plugging in a wifi adapter fix all this problem? please help a newbie out, im frustrated lol
![unknown](https://user-images.githubusercontent.com/67565928/85963500-26b42180-ba0a-11ea-9a0e-2edebeb846dd.png)

**Comment by Tempest3756** [comment]
help pls

**Comment by TsgabiXD** [comment]
maybe
just try it

**Comment by TsgabiXD** [comment]
maybe...
...just try it with another wifi card

I don't know the exact problem, but I think it's a simple internet problem

**Comment by arismelachroinos** [comment]
Not a lscript issue.
