### ISSUE TITLE
L doesn't work

### ISSUE THREAD

**Issue by jpie726** [arismelachroinos/lscript#251]
**Describe the bug**
I successfully installed lazyscript and whenever I go to press "l" it just does the same thing as ls

**To Reproduce**
1. Go to terminal in Ubuntu 20.04
2. Type l once installed
3. See error

**Expected behavior**
Expected behavior would have been to launch the lazyscript

**Screenshots**
Not applicable

**Output of `cat /etc/os-release`**
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Output of `whoami`**
root

**Additional context**
Not applicable

**Comment by arismelachroinos** [comment]
![image](https://user-images.githubusercontent.com/21193898/87275714-64737880-c4e7-11ea-9ea7-bd2cce09f7b2.png)
