### ISSUE TITLE
Lscipt Not Running - Gnome message & IAGREE.txt is displayed

### ISSUE THREAD

**Issue by Empress228** [arismelachroinos/lscript#257]
1. I get the below message after installation.

```
Open a NEW terminal and type 'l' to launch the script

** (gnome-terminal:8348): WARNING **: 15:45:45.285: Failed to connect to the session manager: None of the authentication protocols specified are supported
```
Please see screenshot:
![2020-09-14 15_57_54-Window](https://user-images.githubusercontent.com/20726160/93104104-f5f49780-f69c-11ea-984a-506373f2d252.png)

2. While running the "l" command on a new terminal & entering the "**YES**" command, the below message is displayed as captured.
![Screenshot at 2020-09-14 16-07-40](https://user-images.githubusercontent.com/20726160/93103843-a4e4a380-f69c-11ea-9f6b-237d65045c73.png)

Kindly assist. What next?

**Comment by MiChaelinzo** [comment]
try changing it's permission mine is set into 
-rwxrwxrwx 1 root root     78 Sep 29 00:14 IAGREE.txt

**Comment by jayadav7** [comment]
same issue

**Comment by arismelachroinos** [comment]
The script is only for Kali Linux. You are using Parrot.

**Comment by MiChaelinzo** [comment]
chmod 777 IAGREE.txt is the command
