### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by SarathKpt** [arismelachroinos/lscript#261]
![Screenshot at 2020-09-26 10-16-04](https://user-images.githubusercontent.com/57666232/94330339-34e6ef00-ffb3-11ea-8d05-431627eb0724.png)
i would like to have a new option "ALL" for selecting all tools at a time without without typeing 1 to 99

**Comment by GakunGak** [comment]
Completely agree

**Comment by arismelachroinos** [comment]
I had that feature but took it out. You should only install the tools you need, and you dont need them all.
