### ISSUE TITLE
"/bin/lscript/l: line 6572: /root/script/IAGREE.txt: Permission denied" UNABLE to install lazyscript

### ISSUE THREAD

**Issue by jayadav7** [arismelachroinos/lscript#262]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Output of `cat /etc/os-release`**
Paste the output here.

**Output of `whoami`**
Paste the output here.

**Additional context**

**Comment by arismelachroinos** [comment]
Fill in the issue template. Its there for a reason.
