### ISSUE TITLE
ngrok error 

### ISSUE THREAD

**Issue by tarpdude** [arismelachroinos/lscript#28]
option16

Ngrok is not installed.To install it, go to TOOLS -> Install/reinstall a tool -> ngrok
I get this error but I installed ngrok

**Comment by arismelachroinos** [comment]
did you install it via the script ??

**Comment by arismelachroinos** [comment]
the script searched for a file named 'ngrok' in /root/ .     so if /root/ngrok   exists, then it proceeds with the script. Please take a look at your /root directory and look for a file named ngrok. if it is named 'ngrok1'  or something other than 'ngrok' rename it to 'ngrok' and it should work.

**Comment by arismelachroinos** [comment]
No further info. Changed a minor thing that might caused that.
