### ISSUE TITLE
Can't install or run LazyScript

### ISSUE THREAD

**Issue by VoidMindNSoul** [arismelachroinos/lscript#282]
**Describe the bug**

# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Failed to execute child process “dbus-launch” (No such file or directory)    [{RAW}]

**Comment by arismelachroinos** [comment]
You didn't fill the issue template so I cannot help you 
![image](https://user-images.githubusercontent.com/21193898/100864519-c5075000-349e-11eb-820f-34376ee051a9.png)
