### ISSUE TITLE
Kali Rolling (2020.3) x64

### ISSUE THREAD

**Issue by ghost** [arismelachroinos/lscript#283]
Hello,

My issue:  At the "This tool is only for educational purposes only." screen.

I am Unable to proceed past YES/NO prompt

OUTPUT:

/bin/lscript/l: line 6572: /root/lscript/IAGREE.txt Permission Denied

then it starts at the "Press Any Key to Continue" Page followed by the "This tool is only for educational purposes only." page again.

**Comment by arismelachroinos** [comment]
Please fill in the template when you are creating an issue... What is the output of `whoami` ?

**Comment by ghost** [comment]
Where is the template?

output: kali

**Comment by arismelachroinos** [comment]
![image](https://user-images.githubusercontent.com/21193898/100973700-b1fa8b80-3543-11eb-92c3-d9267722257c.png)
This is the template. Don't fill it now, now its too late.

**Comment by arismelachroinos** [comment]
The issue is that you did not follow the instructions, you are not a root user. I even have a video tutorial on how to install it. Please see that for the proper way to install the script.
