### ISSUE TITLE
Kali Rolling (2020.3) x64

### ISSUE THREAD

**Issue by ghost** [arismelachroinos/lscript#284]
**Describe the bug**
I am unable to proceed past the YES/NO prompt on the  "This is a tool........" page.

**To Reproduce**

1. "Press Any Key to Continue" screen

"2. This is only for educational purposes only" screen.

3.   .......and only with own responsibility: YES/NO

4.  type YES

5.  error output(very fast): bin/lscript/l: line 6572: / root/lscript/IAGREE.txt: Permission Denied

6. "Press Any Key to Continue" page

**Expected behavior**
Expected program to proceed after typing YES

**Screenshots**

**Output of `cat /etc/os-release`**
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.3"
VERSION_ID="2020.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Output of `whoami`**
kali

**Additional context**

**Comment by arismelachroinos** [comment]
The issue is that you did not follow the instructions, you are not a root user. I even have a video tutorial on how to install it. Please see that for the proper way to install the script.

**Comment by ghost** [comment]
Thanks alot.  Youre a star. One last thing.  Where can I find the video you did.  Thanx again. :-)

**Comment by ghost** [comment]
I found it
