### ISSUE TITLE
l doesnt launch lazy script

### ISSUE THREAD

**Issue by HackerBaus** [arismelachroinos/lscript#290]
I know this isn't really an issue with lazy script (i dont really know where else to put it) but when i put L in the terminal in doesnt launch lazy script but it runs the command ls (you know to show all directories in the current folder)
How can i solve this?

**Comment by HackerBaus** [comment]
Oke so i found a work around. if i put /root/lscript/L in the terminal it launches lazyscript but i cannot use "L"

**Comment by Qussayyon** [comment]
> Oke so i found a work around. if i put /root/lscript/L in the terminal it launches lazyscript but i cannot use "L"

try to add alias in `bash` shell:
alias l='/root/lscript'
sorry if this does not work for you.

**Comment by qualk** [comment]
`alias l='/root/lscript/l'`

**Comment by massXaccel** [comment]
that fixed it for me

**Comment by qualk** [comment]
@HackerBaus if fixed close issue if not then comment

**Comment by massXaccel** [comment]
CORRECTION it did NOT work for me. After I exit terminal then bring it back up i have too alias every time a new session starts

**Comment by qualk** [comment]
no put that in the .bashrc at the ls aliases

**Comment by qualk** [comment]
close the issue

**Comment by faisal556677** [comment]
i dont get the .bashrc
