### ISSUE TITLE
Kali linux 2021.1

### ISSUE THREAD

**Issue by zerodev-exe** [arismelachroinos/lscript#310]
when i press the letter "l" it shows the list like if i where to press "ls" so if you could fix that it would be very great.
thank you very much!

**Comment by NicolaLino** [comment]
I have the same problem

**Comment by NicolaLino** [comment]
I found solution 
1. go to lscript directory 
2. type " ./l "

**Comment by CaraTortu** [comment]
The problem is not lscript. The problem is that kali has an alias with the l letter. Just edit .bashrc and remove the l alias.

It will look like this:
l='ls -CF'

**Comment by qkum** [comment]
> The problem is not lscript. The problem is that kali has an alias with the l letter. Just edit .bashrc and remove the l alias.
> 
> It will look like this: l='ls -CF'

**.bashrc file location, hidden file, be sudo (sudo su):**
`/etc/skel/.bashrc`

....
I just commented out the line and rebooted...'l' command still don't work.

How can I otherwise run the program?

**Comment by CaraTortu** [comment]
> > The problem is not lscript. The problem is that kali has an alias with the l letter. Just edit .bashrc and remove the l alias.
> > 
> > It will look like this: l='ls -CF'
> 
> **.bashrc file location, hidden file, be sudo (sudo su):**
> `/etc/skel/.bashrc`
> 
> ....
> I just commented out the line and rebooted...'l' command still don't work.
> 
> How can I otherwise run the program? 

You should edit your home folder bashrc. Located in ~/.bashrc
Edit it as a normal user and you don't need to reboot. You just close the terminal and open it again
