### ISSUE TITLE
FIXED LSCRIPT failed to execute child process error

### ISSUE THREAD

**Issue by ChongChink** [arismelachroinos/lscript#321]
FIRST,
 you have to go to /usr/bin/lscript folder(as root) and then open the 'L' and Lh1 bash file using ur text editor
then change lh1, lh3 and lh4 as done in the images and save it
![1](https://user-images.githubusercontent.com/88436922/136386999-a31ba6ef-d03e-475e-928c-ad73155997ac.PNG)
![2](https://user-images.githubusercontent.com/88436922/136387024-1024ee4d-3ea7-4806-9242-a99949f8f74b.PNG)
 

SECOND,
go to Lh1 script and then change the lh2 as done in the image and save it, yes click on the replace all 

![3](https://user-images.githubusercontent.com/88436922/136387189-8e12b22c-f68a-4e8a-9b05-d5e49936fb2f.PNG)

LASTLY,
open your terminal as root and then type this command (or copy paste it)
alias l='/usr/bin/lscript/l'
alias lh1='/usr/bin/lscript/lh1'
alias lh2='/usr/bin/lscript/lh2'
alias lh3='/usr/bin/lscript/lh3'
alias lh4= '/usr/bin/lscript/lh4'

After doing all those your child procces error should be fixed
 
![5](https://user-images.githubusercontent.com/88436922/136387955-b41963c3-2f6d-4fbb-90a6-47159a0eaeaa.PNG)

found this fix long ago but was too lazy :p

**Comment by sushant96702** [comment]
![image](https://user-images.githubusercontent.com/58913117/152873338-86989b2c-63f3-4a89-97a5-eef57e516572.png)
can u guys help me?
i am still getting issue

**Comment by ChongChink** [comment]
> ![image](https://user-images.githubusercontent.com/58913117/152873338-86989b2c-63f3-4a89-97a5-eef57e516572.png) can u guys help me? i am still getting issue

Don't you have a folder called "lscript" in /usr/bin/    ??
![Capture](https://user-images.githubusercontent.com/88436922/152974266-3d9dd3b0-a6dd-46cb-8934-a35c82ce8888.JPG)
 
 
 IF you dont, then create a folder lscript in /usr/bin/
 and paste all the bash files as given in the image

**Comment by xy14053156** [comment]
> 
please remove the ' ' between = and '
