### ISSUE TITLE
Bug since i install anonym8 or/and anonsurf

### ISSUE THREAD

**Issue by jcdex69** [arismelachroinos/lscript#33]
Hi, 

Since i install anonym8 or/and anonsurf my dns don't work at every reboot
ping don't work for example www.google.fr but work for 216.58.204.227
For my ping work i must enable anonym8 or anonsurf (work with the 2 tools)
for retrieve my wan ip of my isp i disable anonym8 and ping work www.google.fr
sorry for my english

Thx

**Comment by arismelachroinos** [comment]
This is not an issue on me script. it is a common issue with tor related vpns. Some say that it's because you have to have the correct time set. Common issue and not on my side
