### ISSUE TITLE
nWach not working 

### ISSUE THREAD

**Issue by user0257** [arismelachroinos/lscript#34]
i'm using kali 2.0 (the last version)
![screenshot from 2017-09-09 00-58-15](https://user-images.githubusercontent.com/31783556/30235054-a51b3a86-94fb-11e7-81ab-11ad09dd622f.png)

**Comment by Ekultek** [comment]
What does that have to do with this script?

**Comment by arismelachroinos** [comment]
irrelevant

**Comment by user0257** [comment]
I used lazyscript to install nWach but didn't work

**Comment by arismelachroinos** [comment]
@user0257 install new update 2.1.1 and go to tools -> install/reinstall tool    and install nWatch again. If you get error again , i cant do anything. I just added some requirements that may caused the issue.
