### ISSUE TITLE
Sqlmap?

### ISSUE THREAD

**Issue by Ekultek** [arismelachroinos/lscript#36]
Is sqlmap on the tool list?

**Comment by arismelachroinos** [comment]
no it isn't and it is on my todo list. I am planning to add a site menu in tools or something.

**Comment by Ekultek** [comment]
Well I was just thinking, isn't sqlmap already distributed with Kali? If so, it should be in the PATH already, so you could run off of that.

**Comment by Ekultek** [comment]
Any updates on when this will be implemented?

**Comment by Ekultek** [comment]
Also if you’d like a real challenge, you could try to implement [zeus](https://github.com/ekultek/Zeus-Scanner)

**Comment by arismelachroinos** [comment]
@Ekultek Not sure about any update soon, need some more tool suggestions for that. Please recommend the good ones to add. I am not into this site-vulnerability thing so i have no idea what tools are good.

**Comment by Ekultek** [comment]
Sqlmap is a good one, lots of documentation as well so it’s easy to pick up it has a hook to msf as well so it can be called, I’m not sure how easy it would be to implement though just b cause of all the possible flags there are

**Comment by arismelachroinos** [comment]
Yeah lots of flags make it difficult because i dont use those tools and need to do some research. It will be added tough.

**Comment by Ekultek** [comment]
Well I look forward to the push! Let me know if you need any help

**Comment by arismelachroinos** [comment]
Sure

**Comment by arismelachroinos** [comment]
automated script added.
