### ISSUE TITLE
error start lscript

### ISSUE THREAD

**Issue by fuckantivirus** [arismelachroinos/lscript#37]
I installed lscript on kali linux 64bit when I type l in terminal it does not start

**Comment by arismelachroinos** [comment]
are you a root user?
tell me to output of   ls /usr/bin/lscript

**Comment by fuckantivirus** [comment]
yes Im root 
 /usr/bin/lscript: No such file or directory

**Comment by arismelachroinos** [comment]
rm - r /root/lscript  
git clone https://github.com/arismelachroinos/lscript.git
cd /root/lscript
chmod +x install.sh
./install.sh

**Comment by arismelachroinos** [comment]
after that one fails then do a chmod +x l && mkdir /usr/bin/lscript && cp l /usr/bin/lscript
and report me any errors

**Comment by fuckantivirus** [comment]
still does not work 

I tried both steps

**Comment by arismelachroinos** [comment]
'doesn't work' doesn't help me. As I said report errors.

**Comment by fuckantivirus** [comment]
└──╼ #l
4nonimizer/           HT-WPS-Breaker/        spade/
Ad-injector/          Infoga/                SPF/
airgeddon/            IPGeoLocation/         SpyNoteShell/
air-hammer/           JSRat-Py/              sqli-scanner/

**Comment by Ekultek** [comment]
lol am I the only one who's confused as shit right now?

**Comment by arismelachroinos** [comment]
hahahaha what is going on? well I think the issue is on your side. no details no fix.
