### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by Trespasser11** [arismelachroinos/lscript#39]
Hello together!

Could someone explain to me why I do not get an interface displayed as in the description?
![lazy script](https://user-images.githubusercontent.com/32282928/30837143-27c33f6e-a263-11e7-9819-0e611ea008b9.PNG)

Best Regards,
Trespasser

**Comment by arismelachroinos** [comment]
@Trespasser11  hi,
thanks a lot for reporting this issue. can you please message me on https://www.facebook.com/arismelachroinos  ?

**Comment by Trespasser11** [comment]
Thanks a lot to arismelachroinos!

Solved the Problem that was caused by me within seconds.

Best Regards,
Trespasser
