### ISSUE TITLE
Remodeling hard-coded scripts

### ISSUE THREAD

**Issue by joaquingx** [arismelachroinos/lscript#42]
Hey, Let me know what you think about remodeling the install.sh to getting it more general,without hard-coded routes for example. 

I will glad to help with this. 

Joaquin.

**Comment by arismelachroinos** [comment]
Hi , can you please explain what you mean by 'hard-coded routes' ?

**Comment by joaquingx** [comment]
For example in that part, you assume that lscript is in /root /. Also, you can do that part (chmod + cp) with a single **install** command.
```sh
chmod +x /root/lscript/lh1
chmod +x /root/lscript/lh2
chmod +x /root/lscript/lh3
chmod +x /root/lscript/lh31
chmod +x /root/lscript/l
chmod +x /root/lscript/lh4
chmod +x /root/lscript/lh41
chmod +x /root/lscript/lh42
chmod +x /root/lscript/lh43
chmod +x /root/lscript/ls/l131.sh
chmod +x /root/lscript/ls/l132.sh
chmod +x /root/lscript/ls/l133.sh
chmod +x /root/lscript/uninstall.sh
clear
echo -e "Copying script to /bin/lscript"
sleep 1
mkdir /bin/lscript
cd /root/lscript
cp /root/lscript/l /bin/lscript
cp /root/lscript/lh1 /bin/lscript
cp /root/lscript/lh2 /bin/lscript
cp /root/lscript/lh3 /bin/lscript
cp /root/lscript/lh31 /bin/lscript
cp /root/lscript/lh4 /bin/lscript
cp /root/lscript/lh41 /bin/lscript
cp /root/lscript/lh42 /bin/lscript
cp /root/lscript/lh43 /bin/lscript
```

**Comment by arismelachroinos** [comment]
well the /root is the default path that i say on the instructions everyone should clone. Thats used for many temp files and settings and i decided its best to keep the path stable. So I made it so that if you didnt clone it to /root/ then it will do it for you. Now for the install command, i am not really aware of that. What do you mean?

**Comment by joaquingx** [comment]
Okay, I understand. About [install](https://linux.die.net/man/1/install ).

**Comment by arismelachroinos** [comment]
Thanks for your recommendations. Come back to recommend anything you want again.
