### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by mascali33** [arismelachroinos/lscript#44]
Hi, I see you want to do **more** by typing less so I made a bash installer file at  `MascaCorp/LazyScript-Installer` and wanted to know if you are interested in it.  
Normally it work well, so if you have any suggestions submit me an issue on the installer project page.

**Comment by arismelachroinos** [comment]
Thank you for your time sir but I don't really see the point of all this. There are infinite ways to do one thing. So please report any issues you face, and recommend any new feature to be added. Thanks a lot for your time.
