### ISSUE TITLE
Next possible changelog

### ISSUE THREAD

**Issue by arismelachroinos** [arismelachroinos/lscript#48]
2.1.5
WPS scanning menu remade, fixed bugs and added sorting by power.
Fixed pixie dust attack on WPS.
Added autocheck if handshake found every x secs.
Fixed unlock WPS menu errors.
Fixed Fluxion launch error due to latest fluxion version.
Fixed Kwetza installation typo.
Fixed aircrack close after run.
Fixed arp-scan issue.
Remade tool's installation menu. Select multiple tools at the same time, sorted alphabetically too.
Scan found IPs for eternalblue vulnerability.
Type 'gate' to go to router's login page in browser.

**Comment by thehappydinoa** [comment]
@arismelachroinos I would love to contribute, would we be able to dm somehow?

**Comment by arismelachroinos** [comment]
@thehappydinoa Thanks for that, you can create a new issue for any feature you wish to be implemented ,or tool, or issue to be fixed.

**Comment by thehappydinoa** [comment]
Ok, would I be able to add tools myself. Do you accept PRs?

**Comment by arismelachroinos** [comment]
no you can just add it on the issues tab

**Comment by thehappydinoa** [comment]
Ok

**Comment by a7ent** [comment]
*******INSTALL ALL FEATURE********

**Comment by arismelachroinos** [comment]
@a7ent excuse me?

**Comment by zartaz** [comment]
i think @a7ent  wanted menu entry "install all feature"
