### ISSUE TITLE
unable to get past Agree

### ISSUE THREAD

**Issue by gregoryr1** [arismelachroinos/lscript#51]
I've installed the lscript but when it asks me to agree by typing YES it doesn't allow me to continue

**Comment by arismelachroinos** [comment]
@gregoryr1 did you type it in capitals? are you using kali?

**Comment by gregoryr1** [comment]
I wasn't using Kali, no

**Comment by arismelachroinos** [comment]
@Sjuuls  Yes it does. If you use kali as a root user it will find the file.  @gregoryr1  this script is made for kali only

**Comment by gregoryr1** [comment]
Ok thanks for the reply!

**Comment by Sjuuls** [comment]
Hmm, don't know what happened then. I just did a reinstall and all went fine after that.

**Comment by Sjuuls** [comment]
@gregoryr1 I assume you do since the creator said so. On the sidenote, I don't think our problems didn't have a related origin though.

**Comment by gregoryr1** [comment]
Ok got it thanks
