### ISSUE TITLE
Allow Multiple Tool Installs

### ISSUE THREAD

**Issue by KingAbdullah23** [arismelachroinos/lscript#56]
Hey, I think it would be very useful if you could allow the users of the script to multi-select tools and install them simultaneously to a specific directory rather than downloading them one by one. I myself would be grateful if you could take the time to implement this.

**Comment by thehappydinoa** [comment]
I think this would be a great implementation

**Comment by arismelachroinos** [comment]
Hi, thank you for your suggestion. The multi tool selection sounds a nice idea, I don't see the location part to be a big deal though. I think it is more stable to keep everything on root, some tools require that in order to work too, so it will be a mess, don't you agree?

**Comment by KingAbdullah23** [comment]
Yea your actually right, i trued moving some tools around manually and had some errors. So yea i definitely agree that they should be kept in root but the multi tools would be more convenient as you said.

**Comment by Mazo26** [comment]
People, you can just open another window terminal and type "l" and enter, then you can just do the same and install another tool... not so hard :D for new terminal windows shortcut can be alt + ctrl + T :D

**Comment by arismelachroinos** [comment]
@Mazo26  Yes thats true, the script works, it was just a recommendation which will make things just a bit faster (and lazier :P ). I am working on it though.

**Comment by arismelachroinos** [comment]
Feature is ready. Will upload it on the upcoming release.
