### ISSUE TITLE
installing tools to /usr/local/bin so root directory is neat

### ISSUE THREAD

**Issue by SLiM94553** [arismelachroinos/lscript#57]
so ive read that you dont want to get your root directory filled with too many directories as it can potentially cause problems. i know hoe to clone gits outside of the root directory, but upon installing lscript it was still installed in my root directory, as well as all of the software and tools i download through it. is there a way to edit the script so that the tools it installs at least all go to a folder such as /usr/local/bin so my home directory doesnt get cluttered. also, would this potentially cause problems of its own or is there a better place to install the scripts? still new with linux in general and only have a basic understanding of it. AWESOME SCRIPT BY THE WAY

**Comment by arismelachroinos** [comment]
Thank you for recommending, However, many scripts within lscript, require you to install them to root in order for them to work. The possible solution could be to make a dedicated folder for most of the script that support to be installed elsewhere, but I do not think this is really important, you dont have to install all the scripts, just the ones you really want. I haven't noticed any issues with the root directory and if you do, please report back . I may look at this recommendation on another time in the future.

**Comment by SLiM94553** [comment]
Thank you for getting back to me. I appreciate it

Sent from ProtonMail mobile

-------- Original Message --------
