### ISSUE TITLE
doesn't launch

### ISSUE THREAD

**Issue by MichalPlays** [arismelachroinos/lscript#58]
Hi,
I have there an issue with your script.
If I want to start it and type in l then I'm getting only a list which is showing what's inside directory (similar cmd like # dir 

I also got an warning message after installing it which shows me following message

**  (gnome-terminal :8659) : WARNING **: Failed to connect to the session manager: None of the authentication protocols specified are supported 

I'm running at this moment at latest Kali linux release and even tried to launch this script as SU + sudo apt-get update  / apt-get upgrade before installing this script : P 

It would be nice if you would help me with that

**Comment by arismelachroinos** [comment]
Sorry I cannot replicate your issue. This does not happen to me and I am 100% updated. Make sure you are a root user. As far as I know, this ls thing when you type just 'l' , happens in ubuntu
