### ISSUE TITLE
Gloom and SecHub

### ISSUE THREAD

**Issue by KroSStreeT88** [arismelachroinos/lscript#60]
Hey,

First, your script is awesome.  Second, these two can't clone into the repository's.  I don't know if it is my machine, or what the case may be.

**Comment by thehappydinoa** [comment]
Ya I have the same issue

**Comment by arismelachroinos** [comment]
Thanks a lot for reporting. I will take a look at it on my free time

**Comment by Ekultek** [comment]
Are you sure you have all the dependencies for both of them? I’ve got no problem with them

**Comment by KroStudios** [comment]
Yeah I checked it.  again, this could be because of the computer I am on.  I am more than certain its on it's last leg.  She's been a trooper :'(

**Comment by cmkingsh4dow** [comment]
Hi Sir,

Hope this reopens this. I am unable to install both tools. They both have requested a username and password for Github....thanks
