### ISSUE TITLE
aircrack issue

### ISSUE THREAD

**Issue by thetoddy** [arismelachroinos/lscript#61]
Hello guys! First of all, awesome script, and thanks to the developers for making this stuff so easy. I just encountered an annoying issue. When i use aircrack form the script, i get successfully to the part when it scan my .txt file in order to find the password, but when it finds it, that terminal window just closes and i am of course unable to read the psw. Do you guys know how to solve this? I did't find anything like this on the net. Please help! Best regards

**Comment by arismelachroinos** [comment]
Hi, it's just me 😁 thanks a lot for reporting. I will take a look at it as soon as possible

**Comment by arismelachroinos** [comment]
Fix is included on upcoming release
