### ISSUE TITLE
Trying to run on mac

### ISSUE THREAD

**Issue by UsefIbba** [arismelachroinos/lscript#63]
I got this:
l: line 1895: syntax error near unexpected token `)'
l: line 1895: `$YS  2$CE) ssh_login      : Brute-force SSH'
Any ideas?

**Comment by arismelachroinos** [comment]
What did you do to get this error? Do you use latest kali?

**Comment by arismelachroinos** [comment]
@UsefIbba  Thanks for reporting what was the issue...
