### ISSUE TITLE
Anony8 and Anonysurf

### ISSUE THREAD

**Issue by Dylan433447** [arismelachroinos/lscript#64]
Issue is ..
when i reboot my kali linux the anony8 and anonysurf both   auto start their services 
as they auto disable my Resolv.config and it becomes empty ...the internet won't return back unless i disable them from lscript ...
also i tried to remove lscript but their effect still remains  ...Can you solve it?

**Comment by arismelachroinos** [comment]
This has nothing to do with lscript. Contact the developers of those tools, not the launcher of them...
