### ISSUE TITLE
HELLO my issue doesn't relate to lscript just asking experinced people !!

### ISSUE THREAD

**Issue by Dylan433447** [arismelachroinos/lscript#65]
This issue doesn't relate lscript just asking for experinced people =) ,!

please can you tell how to fix this problem ??

this relate to ... ZAmbie toolkit ....

please ! when i run DDoS attack xerxos or any ddos tool it gives me this error 

Traceback (most recent call last):
  File "./zambie.py", line 85, in <module>
    subprocess.call(['./Dos_Attacks/xerxes/xerxes',Domain, Port])
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in _init_
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 why ?﻿

please ! if you understand what does this mean answer me !

**Comment by arismelachroinos** [comment]
Sorry I don't use python, this is totally unrelated as you already know.

**Comment by Ekultek** [comment]
It’s because there’s no such file or directory on your system
