### ISSUE TITLE
Gloom and SecHub

### ISSUE THREAD

**Issue by cmkingsh4dow** [arismelachroinos/lscript#66]
Hi,

I do realise that this issue was closed before. I am unable to install the two tools as they are requesting the username and password. Any solution or advice would be much appreciated. 

Thank you

**Comment by arismelachroinos** [comment]
Sure, I will take a look at it, thank you for reporting

**Comment by cmkingsh4dow** [comment]
Thank you

**Comment by arismelachroinos** [comment]
Sorry for the delay, and you are right. These two repositories are not available now. I found some forks from other people so I will replace the old links. Better this than nothing I guess. Upcoming version will have it fixed.
