### ISSUE TITLE
gnome-terminal: command not found

### ISSUE THREAD

**Issue by applehacker321** [arismelachroinos/lscript#68]
The script gives the following error when installing the script for the first time.

Open a new terminal and type ‘l’ to launch the script
./install.sh: line 104: gnome-terminal: command not found 

I am running Ubuntu mate 16.04.02 LTS

**Comment by arismelachroinos** [comment]
Sorry only Kali is supported.

**Comment by applehacker321** [comment]
Running the latest version of kali, with all repositories upgraded, still give me same error. Pls help

**Comment by arismelachroinos** [comment]
It does not have any problem with me. try installing gnome terminal
