### ISSUE TITLE
anonym8 autostart at boot

### ISSUE THREAD

**Issue by wacs** [arismelachroinos/lscript#70]
On Kali 2017.3 anonym8 autostarts at boot after 30 secs, it causes no internet connection. Only way to disable is running anOFF. After restarting the machine the service autostarts again. Maybe adding some options to choose what services of the lazy script runs at boot would be useful.

**Comment by thehappydinoa** [comment]
Ya I have the same problem, it works on my home network, but when I'm at school it messes with oprnDNS

**Comment by adilshafiq1512** [comment]
same here bro.. what to do ???

**Comment by arismelachroinos** [comment]
This is anonym8's issue. I will not add the feature you requested in the near future. Sorry for that.
