### ISSUE TITLE
unable to run script Kalilinux Nethunter 3.0

### ISSUE THREAD

**Issue by oakes8585** [arismelachroinos/lscript#71]
Chmod +x install.sh
./install.sh
You did not follow githubs instructions i will try to do it for you
Then i answer the next question as first run
After the inital install i type "l" in my terminal as instructed by the end of the install only to get command not found ............

Looks like a great script but it wont run. Any ideas?

**Comment by arismelachroinos** [comment]
nethunter? on an Android? I have tested it and it does not work if you don't have a gui. You cannot do it with just a terminal emulator. try launching it with bash /root/lscript/l   but it's not a proper way and it's very very experimental. Use it on pc for proper behaviour

**Comment by oakes8585** [comment]
Flawless so far and a great time saver..... hope to see mre features in the future. Great work @arismelachroinos

**Comment by arismelachroinos** [comment]
thank you. Yes I have very limited free time due to exams this period. You can submit a feature if you want. thanks

**Comment by arismelachroinos** [comment]
thank you. Yes I have very limited free time due to exams this period. You can submit a feature if you want. thanks

**Comment by arismelachroinos** [comment]
thank you. Yes I have very limited free time due to exams this period. You can submit a feature if you want. thanks

**Comment by oakes8585** [comment]
Would love to see custom scripts included to run and get and working install on nethunter3.0 for nexus 6 for the following
Dendroid
DroidJack and
Androrat

That would be a awsome added feature
