### ISSUE TITLE
doesnt start

### ISSUE THREAD

**Issue by lyrics1988123** [arismelachroinos/lscript#72]
hey, nice script - but i cannot get it running for me.
tried it on parrot and kali, followed the instructions.. but:
after the installation when i run it with "l" the lazyscript starts, but doesnt show any text, menue or something. only the windowtitle..

had the same issue on both OS.. any idea? thank you!

**Comment by arismelachroinos** [comment]
It does not work on parrot, or at least not made to work for that. It should work on Kali. Please double check , try running it from gnome terminal and from xterm. If it is still the same, tell me here.
