### ISSUE TITLE
request

### ISSUE THREAD

**Issue by oakes8585** [arismelachroinos/lscript#73]
Would love to see custom scripts included to run and get a working install on nethunter3.0 for nexus 6 
See what you can come up with to get the dendroid itself would be nice to just press a button and it be up and running
Dendroid
DroidJack and
Androrat

That would be a awsome added feature

**Comment by arismelachroinos** [comment]
Sorry but I cannot do this. I am working only for Kali because that is what I currently have.

**Comment by oakes8585** [comment]
ok just seen this thank you
