### ISSUE TITLE
i2p2.no

### ISSUE THREAD

**Issue by Alec07007** [arismelachroinos/lscript#75]
For some reason I dont know why im getting this problem cannot get the updates from deb.i2p2.no

root@kali:~# sudo apt-get update
Get:1 http://deb.i2p2.no unstable InRelease [12.3 kB]
Err:1 http://deb.i2p2.no unstable InRelease                
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 67ECE5605BCF1346
Hit:2 http://ftp.hands.com/kali kali-rolling InRelease
Reading package lists... Done
W: GPG error: http://deb.i2p2.no unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 67ECE5605BCF1346
E: The repository 'http://deb.i2p2.no unstable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by arismelachroinos** [comment]
This is not related to the script at all. However try going the the errors menu and then select the apt get update error

**Comment by Ekultek** [comment]
sudo -s << EOF
apt-get update
EOF

It will show you the lists that are failing, then do:

cd /etc/apt/
ls -a

Find the ones that are failing and either remove them or update them to the right source

sudo apt-get update 

You should be fine after that

**Comment by Alec07007** [comment]
thank you very much for the answer but unfortunately the command sudo -s << EOF doesent do anything in command port :( please help

**Comment by Ekultek** [comment]
Oops wrong operator, try 

sudo -s >> EOF
apt-get update
EOF

**Comment by Alec07007** [comment]
this is what i got

**Comment by Alec07007** [comment]
root@Alex:~# sudo -s >> EOF
root@Alex:~# apt-get update
E: Failed to fetch http://deb.i2p2.no/dists/unstable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://deb.i2p2.no unstable InRelease' is not signed.

**Comment by Ekultek** [comment]
Okay, so now what do you think you need to do?
