### ISSUE TITLE
Anonsurf and Anon8 don't work

### ISSUE THREAD

**Issue by Mazo26** [arismelachroinos/lscript#77]
Hello friends, I found that in last update of lscript anonsurf and anon8 don't work. To be more precised, Anonsurf start but when I go to internet, it block every possible page and it looks like I have disabled eth adapter or like I have no internet, Anon8 won't start at all...

**Comment by arismelachroinos** [comment]
Hi sir, this is totally unrelated to lscript. It is not this script's fault that other scripts might not function well. Thank you.
