### ISSUE TITLE
Kali on the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by zugazagoitia** [arismelachroinos/lscript#78]
The script isn't being added to the path or at least is not posible to open it by typing "l".
![image](https://user-images.githubusercontent.com/23284823/35485548-936fa94a-0461-11e8-8f4e-77b709dca9b6.png)

**Comment by arismelachroinos** [comment]
did you run the install.sh?

**Comment by ItzZuga** [comment]
Of course, even it's said during the install that the script is added to the path.

**Comment by arismelachroinos** [comment]
@ItzZuga  type    cat ~/.bashrc | grep "bin/lscript" 
and give me the output

**Comment by Allaye** [comment]
this is the output of the command:: export PATH=/bin/lscript:/bin/lscript:/home/Allaye/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath_target_4738984:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/dotnet:/mnt/c/Users/Allaye/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/Allaye/AppData/Local/Microsoft/WindowsApps

**Comment by johnnybolomorgan** [comment]
@Allaye  did this command work

**Comment by amaliciousavage** [comment]
Has a solution been implemented? Maybe rather than having "l" being the default input to launch the script, during the installation progress to define the launch command. Id love to have this script up and running as soon as possible.

**Comment by Qu3st77** [comment]
im having a problem to when I try to install it said ./install.sh: line 104: gnome-terminal: command not found.   after installation is there any fix for this

**Comment by Qu3st77** [comment]
i tried the fix you gave on April 2 and this was the output export PATH=/bin/lscript:/bin/lscript:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath_target_105810187:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/Geth:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/ethan/AppData/Local/Microsoft/WindowsApps
export PATH=/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath_target_105810187:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program
export PATH=/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath_target_105810187:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program
export PATH=/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/bin/lscript:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath_target_105810187:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program

**Comment by Qu3st77** [comment]
so im hoping theres a fix

**Comment by arismelachroinos** [comment]
You need to have gnome-terminal and GUI in general to launch lscript.
