### ISSUE TITLE
Installing Error in Kali Linux Version 2017.1

### ISSUE THREAD

**Issue by Porter007** [arismelachroinos/lscript#8]
The Error when i run ./ install.sh command after fixing permission by command chmod +x and i have root permission during that time. here is the error if you findout any solution please contact me on whatsapp +919935820453. Thank You.

Error: 

"You didn't follow the github's simple install instructions.I will try to do it for you...
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached"

**Comment by arismelachroinos** [comment]
in order to install the script   you need to me in root folder. so the clone on GitHub needs to be in /root/lscript

**Comment by Porter007** [comment]
i did man still its same error read my thread carefully i cleary mentioned it that i had root privilege and also i was in /root folder.

**Comment by Porter007** [comment]
Fix it please

**Comment by arismelachroinos** [comment]
sir, you mentioned that you had root privileges. not that you were in /root folder. try these commands in terminal :
rm - r /root/lscript

cd

git clone https://github.com/arismelachroinos/lscript 

chmod +x /root/lscript/install.sh

bash /root/lscript/install.sh



if this sequence of commands doesn't work out, message me on fb   https://www.facebook.com/arismelachroinos
