### ISSUE TITLE
New Option.

### ISSUE THREAD

**Issue by Suskes** [arismelachroinos/lscript#81]
Please add a "tool installation path" option in the settings menu.
That way we can choose where all the tools get installed, instead of the root directory for better organization.

Thank you for creating this awsome script!

**Comment by arismelachroinos** [comment]
Hi sir, this was requested before and unfortunately I won't be doing that as many tools require to be installed in root, and it would be a pain to start figuring out which ones do and which ones dont. The solution is to install only the tools that you really need, as there are many and most of them do the same thing. Sorry for that, thank you for your recommendation, if you come up with something else, please let me know.

**Comment by thehappydinoa** [comment]
@arismelachroinos if you accept PR's I would be glad to do the grunt work.
