### ISSUE TITLE
link updation

### ISSUE THREAD

**Issue by adilshafiq1512** [arismelachroinos/lscript#83]
please update sechub link in wifi tools .. new link is this https://github.com/cys3c/secHub... previous one is broken maybe ... personally i changed it . and its works

**Comment by adilshafiq1512** [comment]
sorry for in-convince... but its problem in running ... see the screenshot .. 
![screenshot from 2018-02-13 02-25-42](https://user-images.githubusercontent.com/34338792/36120582-7d28d11a-1065-11e8-8552-7e9dfd68eb1b.png)
![Uploading Screenshot from 2018-02-13 02-26-09.png…]()

**Comment by adilshafiq1512** [comment]
previous broken link in sechub is http://github.com/joshDelta/secHub.git

**Comment by adilshafiq1512** [comment]
problem solved manually clone or download sechub https://github.com/cys3c/secHub .. extract.. then give permission chmod +x ./installer.py .. then ./installer.py .. after installation move secHub from root directory to /usr/share .. also renamed secHub to sechub .. work perfectly thanks lazy script.. 
![screenshot from 2018-02-13 02-40-49](https://user-images.githubusercontent.com/34338792/36121388-cf2e2c74-1067-11e8-8c98-c0f3adbf3bfe.png)

**Comment by arismelachroinos** [comment]
Hi sir. Thanks for reporting. Will fix it soon.

**Comment by adilshafiq1512** [comment]
i think sechub and secHub or different tools....
