### ISSUE TITLE
Issue when installing on Kali 

### ISSUE THREAD

**Issue by Lunaous** [arismelachroinos/lscript#85]
Hi,
 When i installed this it all worked until the end when it returned this

`Open a NEW terminal and type 'l' to launch the script
Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
Use “-- ” to terminate the options and put the command line to execute after it.
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: The connection is closed
`
and when i manually launch a new terminal and type 'l' it returned command not found

**Comment by arismelachroinos** [comment]
Thanks for reporting, will fix it soon. However you sould have been able to launch it by manually typing l in a new terminal ( assuming that you followed the installing instructions on github).

**Comment by Lunaous** [comment]
I followed the instructions on Github and when i open a new terminal and type l it just returns command not found

**Comment by thehappydinoa** [comment]
@Lunaous this should not happen, maybe delete all old files and try again

**Comment by arismelachroinos** [comment]
Make sure you are root user and you are using latest kali
