### ISSUE TITLE
Please Help.  Will nor run on Parrot Security

### ISSUE THREAD

**Issue by Mikewins1** [arismelachroinos/lscript#87]
Just installed parrot os and tried to install this aweswome script.  I downloaded the git clone and cd into lscript.  When I hit "l" it opens up like as if I typed "ls".  I then have to type "./l"
when I try to enable wlan1mon this happens
Enabling wlan1mon...
Killing services...
Done.
Starting monitor mode...
Done
bash: ./l: No such file or directory
┌─[✗]─[root@parrot]─[/home/mike/lscript]
└──╼ #
 This is My Favorite script and cant use it

**Comment by Ekultek** [comment]
See the reason for this is because it’s not made for Parrot
