### ISSUE TITLE
Fluxion instalation loop

### ISSUE THREAD

**Issue by vallerydelexy** [arismelachroinos/lscript#88]
Lastest kali rolling

E: package lighttpd has no installation candidate

Missing bc, dhcp, hostapd, lighttpd, php-cgi

Adding missing sources to package manager, please wait
Adding keys.gnupg.net, please wait
Adding pgp.mit.edu.key, please wait

repeating endlessly
Help..

**Comment by arturoigb** [comment]
go to bin/lscript/ open file l
chage line 3116 and .sh

like that
./fluxion.sh

solve the problem

**Comment by arismelachroinos** [comment]
Fixed with latest update 2.1.5
