### ISSUE TITLE
Script Does not Work in Ubuntu Linux

### ISSUE THREAD

**Issue by vatsal18** [arismelachroinos/lscript#9]
Script Does not Work in Ubuntu Linux

**Comment by arismelachroinos** [comment]
I dont have ubuntu installed , this script is only for kali . If you help me a bit , I may add support for ubuntu too. Message me on https://www.facebook.com/arismelachroinos .  Also try the command :  bash /bin/lscript/l

**Comment by amanesis** [comment]
Ισχύει το ίδιο και για το Parrot ή κάνω κάτι λάθος στην εγκατάσταση;

**Comment by arismelachroinos** [comment]
Προς το παρόν είναι μόνο για Kali. Προσπάθησες να το κανεις εγκατάσταση στο Parrot?

**Comment by amanesis** [comment]
Ναι και μου πετάει αυτό :

 ** (gnome-terminal:3276): WARNING **: Failed to connect to the session manager: None of the authentication protocols specified are supported.

**Comment by arismelachroinos** [comment]
πατησες chmod +x install.sh && ./install.sh    ?

**Comment by amanesis** [comment]
Ναι κανονικά.

**Comment by arismelachroinos** [comment]
Είσαι σίγουρος οτι είσαι root user ?  πρεπει να εισαι. δοκιμασε να γραψεις     su --login      πριν κανεις ./install.sh

**Comment by arismelachroinos** [comment]
μονο αν δεν δουλεψει ουτε αυτο , δοκιμασε το :       bash /root/lscript/l

**Comment by amanesis** [comment]
Ναι ήμουν root. 
Δούλεψε τελικά με το bash /root/lscript/l.
Ευχαριστώ για την βοήθεια :)
