### ISSUE TITLE
./install.sh: line 104: gnome-terminal: command not found

### ISSUE THREAD

**Issue by adamskh21** [arismelachroinos/lscript#92]
When I going through the installation is says: Type "l" to start the lazy script.... 
but then I get ./install.sh: line 104: gnome-terminal: command not found 

PLEASE HELP

**Comment by thehappydinoa** [comment]
This just means you aren't using gnome as your desktop environment... Lscript was hard-coded for vanilla kali

**Comment by arismelachroinos** [comment]
@thehappydinoa  correct

**Comment by ShayBox** [comment]
So is this getting fixed any time soon, since kali now officially has other desktops, and the official vmware & vbox images are xfce, it seems like as good of time as any to have a simple function to check which terminal you have installed.

**Comment by AdamX122** [comment]
@arismelachroinos Is it possible to be used on a Kali linux VM?

**Comment by te4r-0** [comment]
Hello who is this?
