### ISSUE TITLE
Wash not returning information after pressing ctrl+c

### ISSUE THREAD

**Issue by itsme199** [arismelachroinos/lscript#94]
When running wash to locate WPS networks, it correctly shows the networks, but after pressing ctrl+c nothing is passed back to the terminal and nothing is available to select

**Comment by arismelachroinos** [comment]
Thank you for reporting. However I cannot replicate your issue. Make sure you are using latest Kali on PC / VM  as a root user, and also installing it correctly on /root

**Comment by arismelachroinos** [comment]
Okay I did face this issue as well.

**Comment by Giannizzero** [comment]
I have the same problem ;(

**Comment by arismelachroinos** [comment]
@itsme199 @Giannizzero  I fixed this issue, will upload the next version in the next days

**Comment by Giannizzero** [comment]
thank you, i am waiting for your update

**Comment by arismelachroinos** [comment]
@Giannizzero 
@itsme199 
Fixed with latest update 2.1.5
