### ISSUE TITLE
Cannot create a standalone directory in Kali 

### ISSUE THREAD

**Issue by BioFunker** [arismelachroinos/lscript#96]
Hey, nice tool to get an overview of many pentest tools -good job!
I cannot seem to install the script into a dedicated folder in /root/DedicatedFolder.
I can clone the script and `chmod` the install script but when I `./install.sh` a message pops up:
`You didn't follow the github's simple install instructions.I will try to do it for you...` 
at which point I `CTRL+C`ed and sent you this message ;)

I don't want to install in the /home directory as each install just adds a new folder - way too messy.

Any suggestions?

**Comment by BioFunker** [comment]
Thanks @thehappydinoa.
Having looked at the code, the dev has configured everything in `/root/...`.
All the scripts are written to be added to `/root/`.
I suppose I could change every single entry - probably will if I ever  get the time and make a pull request.
Perhaps I should recommend this as a feature.
Anyway -this is a nifty little package.
Thanks.

**Comment by thehappydinoa** [comment]
@BioFunker also I have tried to open a PR, but arismelachroinos is not open to accepting them so you might want to make your own fork.
